# Generated by Django 4.2 on 2023-05-09 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0003_system_information_subcategories_alter_client_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('UT', 'Utah'), ('GA', 'Georgia'), ('PR', 'Puerto Rico'), ('FL', 'Florida'), ('RI', 'Rhode Island'), ('AS', 'American Samoa'), ('GU', 'Guam'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('NC', 'North Carolina'), ('CT', 'Connecticut'), ('DC', 'District of Columbia'), ('MI', 'Michigan'), ('NM', 'New Mexico'), ('NV', 'Nevada'), ('ND', 'North Dakota'), ('OK', 'Oklahoma'), ('NE', 'Nebraska'), ('CO', 'Colorado'), ('MA', 'Massachusetts'), ('SD', 'South Dakota'), ('MD', 'Maryland'), ('VT', 'Vermont'), ('IN', 'Indiana'), ('NY', 'New York'), ('NH', 'New Hampshire'), ('WA', 'Washington'), ('IA', 'Iowa'), ('NJ', 'New Jersey'), ('HI', 'Hawaii'), ('LA', 'Louisiana'), ('MT', 'Montana'), ('UM', 'United States Minor Outlying Islands'), ('TX', 'Texas'), ('MS', 'Mississippi'), ('VI', 'U.S. Virgin Islands'), ('ME', 'Maine'), ('MO', 'Missouri'), ('SC', 'South Carolina'), ('AL', 'Alabama'), ('DE', 'Delaware'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('AZ', 'Arizona'), ('VA', 'Virginia'), ('CA', 'California'), ('AK', 'Alaska'), ('ID', 'Idaho'), ('WY', 'Wyoming'), ('OH', 'Ohio'), ('PA', 'Pennsylvania'), ('TN', 'Tennessee'), ('IL', 'Illinois'), ('OR', 'Oregon'), ('AR', 'Arkansas'), ('MN', 'Minnesota'), ('MP', 'Northern Mariana Islands')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
    ]
