# Generated by Django 4.2 on 2023-05-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0009_implementationstatus_alter_client_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlOrigination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origination', models.CharField(choices=[('Service Provider Corporate', 'Service Provider Corporate'), ('Service Provider System Specific', 'Service Provider System Specific'), ('Service Provider Hybrid', 'Service Provider Hybrid'), ('Configured by Customer', 'Configured by Customer'), ('Provided by Customer', 'Provided by Customer'), ('Shared', 'Shared'), ('Inherited', 'Inherited')], max_length=50)),
            ],
            options={
                'verbose_name': 'Control Origination',
                'verbose_name_plural': 'Control Originations',
            },
        ),
        migrations.AlterModelOptions(
            name='implementationstatus',
            options={'verbose_name': 'Implementation Status', 'verbose_name_plural': 'Implementation Statuses'},
        ),
        migrations.RemoveField(
            model_name='controlimplementation',
            name='origination',
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('VA', 'Virginia'), ('FL', 'Florida'), ('LA', 'Louisiana'), ('PA', 'Pennsylvania'), ('DC', 'District of Columbia'), ('NY', 'New York'), ('NC', 'North Carolina'), ('MP', 'Northern Mariana Islands'), ('NV', 'Nevada'), ('WI', 'Wisconsin'), ('VT', 'Vermont'), ('NE', 'Nebraska'), ('WY', 'Wyoming'), ('IA', 'Iowa'), ('GA', 'Georgia'), ('OR', 'Oregon'), ('WV', 'West Virginia'), ('CO', 'Colorado'), ('AK', 'Alaska'), ('ID', 'Idaho'), ('MS', 'Mississippi'), ('CT', 'Connecticut'), ('MT', 'Montana'), ('AS', 'American Samoa'), ('IN', 'Indiana'), ('NM', 'New Mexico'), ('MN', 'Minnesota'), ('MI', 'Michigan'), ('ND', 'North Dakota'), ('ME', 'Maine'), ('MA', 'Massachusetts'), ('UT', 'Utah'), ('KY', 'Kentucky'), ('RI', 'Rhode Island'), ('WA', 'Washington'), ('SD', 'South Dakota'), ('GU', 'Guam'), ('MO', 'Missouri'), ('AZ', 'Arizona'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('NJ', 'New Jersey'), ('PR', 'Puerto Rico'), ('OK', 'Oklahoma'), ('HI', 'Hawaii'), ('SC', 'South Carolina'), ('UM', 'United States Minor Outlying Islands'), ('VI', 'U.S. Virgin Islands'), ('AR', 'Arkansas'), ('NH', 'New Hampshire'), ('CA', 'California'), ('AL', 'Alabama'), ('OH', 'Ohio'), ('IL', 'Illinois'), ('KS', 'Kansas'), ('DE', 'Delaware'), ('MD', 'Maryland')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='controlimplementation',
            name='originations',
            field=models.ManyToManyField(to='AlchemyApp.controlorigination'),
        ),
    ]
