# Generated by Django 4.2 on 2023-05-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0016_alter_client_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('PA', 'Pennsylvania'), ('KY', 'Kentucky'), ('MD', 'Maryland'), ('UM', 'United States Minor Outlying Islands'), ('MO', 'Missouri'), ('AL', 'Alabama'), ('OK', 'Oklahoma'), ('DC', 'District of Columbia'), ('VI', 'U.S. Virgin Islands'), ('GU', 'Guam'), ('ME', 'Maine'), ('CT', 'Connecticut'), ('UT', 'Utah'), ('MI', 'Michigan'), ('MS', 'Mississippi'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NY', 'New York'), ('SC', 'South Carolina'), ('TX', 'Texas'), ('VA', 'Virginia'), ('NH', 'New Hampshire'), ('AZ', 'Arizona'), ('NC', 'North Carolina'), ('OR', 'Oregon'), ('TN', 'Tennessee'), ('DE', 'Delaware'), ('WV', 'West Virginia'), ('MN', 'Minnesota'), ('OH', 'Ohio'), ('GA', 'Georgia'), ('AK', 'Alaska'), ('WA', 'Washington'), ('PR', 'Puerto Rico'), ('NJ', 'New Jersey'), ('HI', 'Hawaii'), ('KS', 'Kansas'), ('ND', 'North Dakota'), ('IN', 'Indiana'), ('IL', 'Illinois'), ('MP', 'Northern Mariana Islands'), ('SD', 'South Dakota'), ('FL', 'Florida'), ('IA', 'Iowa'), ('RI', 'Rhode Island'), ('LA', 'Louisiana'), ('CA', 'California'), ('WI', 'Wisconsin'), ('ID', 'Idaho'), ('MA', 'Massachusetts'), ('CO', 'Colorado'), ('NM', 'New Mexico'), ('VT', 'Vermont'), ('AS', 'American Samoa'), ('NV', 'Nevada'), ('WY', 'Wyoming'), ('AR', 'Arkansas')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
    ]
