# Generated by Django 4.2 on 2023-06-08 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0020_alter_client_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('VA', 'Virginia'), ('DE', 'Delaware'), ('RI', 'Rhode Island'), ('PR', 'Puerto Rico'), ('TX', 'Texas'), ('NM', 'New Mexico'), ('MI', 'Michigan'), ('WI', 'Wisconsin'), ('AR', 'Arkansas'), ('WY', 'Wyoming'), ('MS', 'Mississippi'), ('KY', 'Kentucky'), ('IA', 'Iowa'), ('OR', 'Oregon'), ('GU', 'Guam'), ('LA', 'Louisiana'), ('PA', 'Pennsylvania'), ('NV', 'Nevada'), ('UM', 'United States Minor Outlying Islands'), ('MA', 'Massachusetts'), ('IN', 'Indiana'), ('VT', 'Vermont'), ('OK', 'Oklahoma'), ('AZ', 'Arizona'), ('SC', 'South Carolina'), ('GA', 'Georgia'), ('MT', 'Montana'), ('DC', 'District of Columbia'), ('CO', 'Colorado'), ('NJ', 'New Jersey'), ('KS', 'Kansas'), ('WV', 'West Virginia'), ('FL', 'Florida'), ('AS', 'American Samoa'), ('MD', 'Maryland'), ('MO', 'Missouri'), ('ND', 'North Dakota'), ('MN', 'Minnesota'), ('IL', 'Illinois'), ('TN', 'Tennessee'), ('OH', 'Ohio'), ('UT', 'Utah'), ('AK', 'Alaska'), ('HI', 'Hawaii'), ('NH', 'New Hampshire'), ('AL', 'Alabama'), ('ME', 'Maine'), ('CT', 'Connecticut'), ('ID', 'Idaho'), ('SD', 'South Dakota'), ('MP', 'Northern Mariana Islands'), ('NY', 'New York'), ('NC', 'North Carolina'), ('WA', 'Washington'), ('VI', 'U.S. Virgin Islands'), ('NE', 'Nebraska'), ('CA', 'California')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='controlimplementation',
            name='control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_implementation', to='AlchemyApp.nistcontrol'),
        ),
        migrations.AlterField(
            model_name='nistcontrol',
            name='control_family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_controls', to='AlchemyApp.controlfamily'),
        ),
    ]
