# Generated by Django 4.2 on 2023-06-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0023_alter_client_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('MI', 'Michigan'), ('OR', 'Oregon'), ('UM', 'United States Minor Outlying Islands'), ('NV', 'Nevada'), ('TN', 'Tennessee'), ('LA', 'Louisiana'), ('VA', 'Virginia'), ('VI', 'U.S. Virgin Islands'), ('MT', 'Montana'), ('MO', 'Missouri'), ('NH', 'New Hampshire'), ('WI', 'Wisconsin'), ('DC', 'District of Columbia'), ('MS', 'Mississippi'), ('OH', 'Ohio'), ('FL', 'Florida'), ('TX', 'Texas'), ('MP', 'Northern Mariana Islands'), ('PR', 'Puerto Rico'), ('HI', 'Hawaii'), ('UT', 'Utah'), ('VT', 'Vermont'), ('MN', 'Minnesota'), ('DE', 'Delaware'), ('RI', 'Rhode Island'), ('NJ', 'New Jersey'), ('SC', 'South Carolina'), ('AK', 'Alaska'), ('CT', 'Connecticut'), ('WV', 'West Virginia'), ('GA', 'Georgia'), ('NM', 'New Mexico'), ('WY', 'Wyoming'), ('KY', 'Kentucky'), ('OK', 'Oklahoma'), ('AZ', 'Arizona'), ('IN', 'Indiana'), ('SD', 'South Dakota'), ('GU', 'Guam'), ('ND', 'North Dakota'), ('IL', 'Illinois'), ('WA', 'Washington'), ('ID', 'Idaho'), ('MD', 'Maryland'), ('NE', 'Nebraska'), ('CA', 'California'), ('AS', 'American Samoa'), ('AL', 'Alabama'), ('MA', 'Massachusetts'), ('AR', 'Arkansas'), ('ME', 'Maine'), ('NC', 'North Carolina'), ('CO', 'Colorado'), ('NY', 'New York'), ('IA', 'Iowa'), ('PA', 'Pennsylvania'), ('KS', 'Kansas')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
    ]
