# Generated by Django 4.2 on 2023-06-26 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0026_alter_controlfamily_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('NC', 'North Carolina'), ('NE', 'Nebraska'), ('DC', 'District of Columbia'), ('IA', 'Iowa'), ('ME', 'Maine'), ('WA', 'Washington'), ('NH', 'New Hampshire'), ('MS', 'Mississippi'), ('MN', 'Minnesota'), ('LA', 'Louisiana'), ('WV', 'West Virginia'), ('IL', 'Illinois'), ('GU', 'Guam'), ('HI', 'Hawaii'), ('NJ', 'New Jersey'), ('MA', 'Massachusetts'), ('CT', 'Connecticut'), ('GA', 'Georgia'), ('OH', 'Ohio'), ('UM', 'United States Minor Outlying Islands'), ('CO', 'Colorado'), ('OK', 'Oklahoma'), ('MD', 'Maryland'), ('AZ', 'Arizona'), ('ID', 'Idaho'), ('MP', 'Northern Mariana Islands'), ('MT', 'Montana'), ('ND', 'North Dakota'), ('UT', 'Utah'), ('PR', 'Puerto Rico'), ('NM', 'New Mexico'), ('NV', 'Nevada'), ('TX', 'Texas'), ('WI', 'Wisconsin'), ('PA', 'Pennsylvania'), ('NY', 'New York'), ('KY', 'Kentucky'), ('AS', 'American Samoa'), ('IN', 'Indiana'), ('OR', 'Oregon'), ('AL', 'Alabama'), ('VA', 'Virginia'), ('FL', 'Florida'), ('MI', 'Michigan'), ('RI', 'Rhode Island'), ('WY', 'Wyoming'), ('VI', 'U.S. Virgin Islands'), ('DE', 'Delaware'), ('CA', 'California'), ('AK', 'Alaska'), ('VT', 'Vermont'), ('KS', 'Kansas'), ('AR', 'Arkansas'), ('MO', 'Missouri'), ('SC', 'South Carolina'), ('TN', 'Tennessee'), ('SD', 'South Dakota')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
        migrations.CreateModel(
            name='FedRAMPParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='AlchemyApp.nistcontrol')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='AlchemyApp.nistcontrolpart')),
            ],
            options={
                'verbose_name': 'Parameter',
                'verbose_name_plural': 'Parameters',
            },
        ),
    ]
