# Generated by Django 4.2 on 2023-06-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0028_alter_client_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('KY', 'Kentucky'), ('NC', 'North Carolina'), ('WI', 'Wisconsin'), ('NE', 'Nebraska'), ('GA', 'Georgia'), ('CO', 'Colorado'), ('TN', 'Tennessee'), ('AZ', 'Arizona'), ('ME', 'Maine'), ('OR', 'Oregon'), ('UT', 'Utah'), ('CT', 'Connecticut'), ('LA', 'Louisiana'), ('FL', 'Florida'), ('WA', 'Washington'), ('UM', 'United States Minor Outlying Islands'), ('MS', 'Mississippi'), ('AS', 'American Samoa'), ('HI', 'Hawaii'), ('IN', 'Indiana'), ('PA', 'Pennsylvania'), ('SC', 'South Carolina'), ('MT', 'Montana'), ('NJ', 'New Jersey'), ('MI', 'Michigan'), ('NM', 'New Mexico'), ('SD', 'South Dakota'), ('WV', 'West Virginia'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('IL', 'Illinois'), ('OK', 'Oklahoma'), ('GU', 'Guam'), ('MP', 'Northern Mariana Islands'), ('KS', 'Kansas'), ('VT', 'Vermont'), ('DC', 'District of Columbia'), ('AR', 'Arkansas'), ('WY', 'Wyoming'), ('ND', 'North Dakota'), ('TX', 'Texas'), ('VA', 'Virginia'), ('NH', 'New Hampshire'), ('NY', 'New York'), ('MO', 'Missouri'), ('DE', 'Delaware'), ('MN', 'Minnesota'), ('CA', 'California'), ('PR', 'Puerto Rico'), ('OH', 'Ohio'), ('AK', 'Alaska'), ('IA', 'Iowa'), ('VI', 'U.S. Virgin Islands'), ('ID', 'Idaho'), ('NV', 'Nevada'), ('RI', 'Rhode Island'), ('AL', 'Alabama')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
    ]
