# Generated by Django 4.2 on 2023-07-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0029_alter_client_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('NE', 'Nebraska'), ('VA', 'Virginia'), ('AR', 'Arkansas'), ('NY', 'New York'), ('MO', 'Missouri'), ('AS', 'American Samoa'), ('MI', 'Michigan'), ('LA', 'Louisiana'), ('MA', 'Massachusetts'), ('TX', 'Texas'), ('CO', 'Colorado'), ('MN', 'Minnesota'), ('KS', 'Kansas'), ('DE', 'Delaware'), ('NH', 'New Hampshire'), ('SD', 'South Dakota'), ('NC', 'North Carolina'), ('AL', 'Alabama'), ('IN', 'Indiana'), ('ND', 'North Dakota'), ('AZ', 'Arizona'), ('RI', 'Rhode Island'), ('TN', 'Tennessee'), ('NJ', 'New Jersey'), ('VI', 'U.S. Virgin Islands'), ('HI', 'Hawaii'), ('NM', 'New Mexico'), ('NV', 'Nevada'), ('AK', 'Alaska'), ('OK', 'Oklahoma'), ('CT', 'Connecticut'), ('FL', 'Florida'), ('PA', 'Pennsylvania'), ('MT', 'Montana'), ('PR', 'Puerto Rico'), ('VT', 'Vermont'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('UT', 'Utah'), ('WY', 'Wyoming'), ('MS', 'Mississippi'), ('WI', 'Wisconsin'), ('WA', 'Washington'), ('ME', 'Maine'), ('DC', 'District of Columbia'), ('UM', 'United States Minor Outlying Islands'), ('GA', 'Georgia'), ('KY', 'Kentucky'), ('OH', 'Ohio'), ('SC', 'South Carolina'), ('IA', 'Iowa'), ('MP', 'Northern Mariana Islands'), ('CA', 'California'), ('MD', 'Maryland'), ('WV', 'West Virginia'), ('GU', 'Guam'), ('OR', 'Oregon')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='controlorigination',
            name='origination',
            field=models.CharField(choices=[('Service Provider Corporate', 'Service Provider Corporate'), ('Service Provider System Specific', 'Service Provider System Specific'), ('Service Provider Hybrid', 'Service Provider Hybrid (Corporate and System Specific)'), ('Configured by Customer', 'Configured by Customer (Customer System Specific)'), ('Provided by Customer', 'Provided by Customer (Customer System Specific)'), ('Shared', 'Shared (Service Provider and Customer Responsibility)'), ('Inherited', 'Inherited from pre-existing FedRAMP Authorization for [Click here to enter text], Date of Authorization')], max_length=50),
        ),
    ]
