# Generated by Django 4.2 on 2023-07-05 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0030_alter_client_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fedrampparameter',
            name='part',
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('AR', 'Arkansas'), ('IN', 'Indiana'), ('NE', 'Nebraska'), ('VT', 'Vermont'), ('NH', 'New Hampshire'), ('OR', 'Oregon'), ('PR', 'Puerto Rico'), ('LA', 'Louisiana'), ('KY', 'Kentucky'), ('AZ', 'Arizona'), ('MD', 'Maryland'), ('MO', 'Missouri'), ('NM', 'New Mexico'), ('PA', 'Pennsylvania'), ('MP', 'Northern Mariana Islands'), ('VI', 'U.S. Virgin Islands'), ('HI', 'Hawaii'), ('MI', 'Michigan'), ('UT', 'Utah'), ('MS', 'Mississippi'), ('AS', 'American Samoa'), ('AL', 'Alabama'), ('SD', 'South Dakota'), ('TX', 'Texas'), ('DC', 'District of Columbia'), ('GA', 'Georgia'), ('FL', 'Florida'), ('NY', 'New York'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('TN', 'Tennessee'), ('GU', 'Guam'), ('SC', 'South Carolina'), ('MA', 'Massachusetts'), ('OK', 'Oklahoma'), ('WA', 'Washington'), ('IA', 'Iowa'), ('WV', 'West Virginia'), ('CA', 'California'), ('ID', 'Idaho'), ('KS', 'Kansas'), ('ND', 'North Dakota'), ('NV', 'Nevada'), ('AK', 'Alaska'), ('MT', 'Montana'), ('RI', 'Rhode Island'), ('NJ', 'New Jersey'), ('CO', 'Colorado'), ('VA', 'Virginia'), ('NC', 'North Carolina'), ('MN', 'Minnesota'), ('CT', 'Connecticut'), ('ME', 'Maine'), ('UM', 'United States Minor Outlying Islands'), ('IL', 'Illinois'), ('DE', 'Delaware'), ('OH', 'Ohio')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
        migrations.CreateModel(
            name='NISTControlElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=2)),
                ('description', models.TextField()),
                ('level', models.IntegerField(default=0)),
                ('control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='AlchemyApp.nistcontrol')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_elements', to='AlchemyApp.nistcontrolelement')),
            ],
            options={
                'verbose_name': 'Control Element',
                'verbose_name_plural': 'Control Elements',
                'ordering': ['identifier'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='controlimplementationstatement',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='controlimplementationstatement',
            name='control_element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AlchemyApp.nistcontrolelement'),
        ),
        migrations.AddField(
            model_name='fedrampparameter',
            name='element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='AlchemyApp.nistcontrolelement'),
        ),
        migrations.AlterUniqueTogether(
            name='controlimplementationstatement',
            unique_together={('control_implementation', 'control_element')},
        ),
        migrations.RemoveField(
            model_name='controlimplementationstatement',
            name='control_part',
        ),
        migrations.DeleteModel(
            name='NISTControlPart',
        ),
    ]
