# Generated by Django 4.2 on 2023-07-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0033_alter_client_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='nistcontrol',
            name='related_controls',
            field=models.ManyToManyField(blank=True, to='AlchemyApp.nistcontrol'),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('ND', 'North Dakota'), ('TX', 'Texas'), ('SC', 'South Carolina'), ('VT', 'Vermont'), ('NC', 'North Carolina'), ('OK', 'Oklahoma'), ('UM', 'United States Minor Outlying Islands'), ('WI', 'Wisconsin'), ('TN', 'Tennessee'), ('ID', 'Idaho'), ('GU', 'Guam'), ('SD', 'South Dakota'), ('IA', 'Iowa'), ('OR', 'Oregon'), ('WV', 'West Virginia'), ('AR', 'Arkansas'), ('AZ', 'Arizona'), ('NV', 'Nevada'), ('NE', 'Nebraska'), ('DE', 'Delaware'), ('KS', 'Kansas'), ('UT', 'Utah'), ('IL', 'Illinois'), ('MA', 'Massachusetts'), ('MO', 'Missouri'), ('CT', 'Connecticut'), ('ME', 'Maine'), ('VA', 'Virginia'), ('WA', 'Washington'), ('MS', 'Mississippi'), ('GA', 'Georgia'), ('IN', 'Indiana'), ('MT', 'Montana'), ('MN', 'Minnesota'), ('NY', 'New York'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('MD', 'Maryland'), ('OH', 'Ohio'), ('MP', 'Northern Mariana Islands'), ('AK', 'Alaska'), ('CA', 'California'), ('VI', 'U.S. Virgin Islands'), ('CO', 'Colorado'), ('NM', 'New Mexico'), ('RI', 'Rhode Island'), ('AS', 'American Samoa'), ('AL', 'Alabama'), ('PA', 'Pennsylvania'), ('PR', 'Puerto Rico'), ('LA', 'Louisiana'), ('NJ', 'New Jersey'), ('NH', 'New Hampshire'), ('KY', 'Kentucky'), ('WY', 'Wyoming'), ('HI', 'Hawaii'), ('MI', 'Michigan')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
    ]
