# Generated by Django 4.2 on 2023-07-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0037_system_service_model_alter_client_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='impact_level',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('VA', 'Virginia'), ('NY', 'New York'), ('AR', 'Arkansas'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('NV', 'Nevada'), ('OK', 'Oklahoma'), ('NM', 'New Mexico'), ('ND', 'North Dakota'), ('PA', 'Pennsylvania'), ('SC', 'South Carolina'), ('HI', 'Hawaii'), ('NJ', 'New Jersey'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('VT', 'Vermont'), ('MS', 'Mississippi'), ('WV', 'West Virginia'), ('AK', 'Alaska'), ('MD', 'Maryland'), ('NH', 'New Hampshire'), ('OH', 'Ohio'), ('WI', 'Wisconsin'), ('KS', 'Kansas'), ('ME', 'Maine'), ('AS', 'American Samoa'), ('NC', 'North Carolina'), ('DE', 'Delaware'), ('AZ', 'Arizona'), ('MP', 'Northern Mariana Islands'), ('MN', 'Minnesota'), ('RI', 'Rhode Island'), ('GU', 'Guam'), ('ID', 'Idaho'), ('LA', 'Louisiana'), ('NE', 'Nebraska'), ('TX', 'Texas'), ('CA', 'California'), ('DC', 'District of Columbia'), ('UM', 'United States Minor Outlying Islands'), ('IN', 'Indiana'), ('KY', 'Kentucky'), ('IA', 'Iowa'), ('WA', 'Washington'), ('MO', 'Missouri'), ('OR', 'Oregon'), ('PR', 'Puerto Rico'), ('AL', 'Alabama'), ('VI', 'U.S. Virgin Islands'), ('MT', 'Montana'), ('CO', 'Colorado'), ('UT', 'Utah'), ('CT', 'Connecticut'), ('IL', 'Illinois'), ('GA', 'Georgia'), ('WY', 'Wyoming'), ('FL', 'Florida')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='system',
            name='environment',
            field=models.CharField(blank=True, choices=[('On-Premises', 'On-Premises'), ('Cloud-Based', 'Cloud-Based'), ('Hybrid', 'Hybrid')], max_length=20, null=True),
        ),
    ]
