# Generated by Django 4.2 on 2023-08-20 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0039_alter_client_state_alter_system_impact_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='NISTControlParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NIST_parameters', to='AlchemyApp.nistcontrol')),
                ('element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NIST_parameters', to='AlchemyApp.nistcontrolelement')),
            ],
            options={
                'verbose_name': 'Parameter',
                'verbose_name_plural': 'Parameters',
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('MT', 'Montana'), ('TX', 'Texas'), ('NC', 'North Carolina'), ('NY', 'New York'), ('PA', 'Pennsylvania'), ('TN', 'Tennessee'), ('NE', 'Nebraska'), ('ID', 'Idaho'), ('FL', 'Florida'), ('IN', 'Indiana'), ('AR', 'Arkansas'), ('NM', 'New Mexico'), ('WY', 'Wyoming'), ('AK', 'Alaska'), ('OK', 'Oklahoma'), ('UT', 'Utah'), ('GA', 'Georgia'), ('OH', 'Ohio'), ('PR', 'Puerto Rico'), ('IL', 'Illinois'), ('MS', 'Mississippi'), ('RI', 'Rhode Island'), ('MO', 'Missouri'), ('AZ', 'Arizona'), ('VI', 'U.S. Virgin Islands'), ('MI', 'Michigan'), ('CT', 'Connecticut'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('ND', 'North Dakota'), ('WA', 'Washington'), ('LA', 'Louisiana'), ('IA', 'Iowa'), ('AS', 'American Samoa'), ('KS', 'Kansas'), ('MA', 'Massachusetts'), ('SD', 'South Dakota'), ('KY', 'Kentucky'), ('MP', 'Northern Mariana Islands'), ('GU', 'Guam'), ('VA', 'Virginia'), ('HI', 'Hawaii'), ('OR', 'Oregon'), ('VT', 'Vermont'), ('ME', 'Maine'), ('SC', 'South Carolina'), ('CO', 'Colorado'), ('NV', 'Nevada'), ('AL', 'Alabama'), ('MN', 'Minnesota'), ('DC', 'District of Columbia'), ('DE', 'Delaware'), ('UM', 'United States Minor Outlying Islands'), ('CA', 'California'), ('MD', 'Maryland'), ('WV', 'West Virginia'), ('WI', 'Wisconsin')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
        migrations.DeleteModel(
            name='FedRAMPParameter',
        ),
    ]
