# Generated by Django 4.2 on 2023-05-08 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0002_informationcategory_alter_answer_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='information_subcategories',
            field=models.ManyToManyField(blank=True, help_text='The information subcategories that flow through the system.', related_name='system_information_subcategories', related_query_name='system', to='AlchemyApp.informationsubcategory', verbose_name='information subcategories'),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('PR', 'Puerto Rico'), ('MA', 'Massachusetts'), ('KS', 'Kansas'), ('AS', 'American Samoa'), ('KY', 'Kentucky'), ('MP', 'Northern Mariana Islands'), ('GA', 'Georgia'), ('MN', 'Minnesota'), ('CA', 'California'), ('AL', 'Alabama'), ('AZ', 'Arizona'), ('CT', 'Connecticut'), ('UT', 'Utah'), ('GU', 'Guam'), ('OK', 'Oklahoma'), ('NV', 'Nevada'), ('AR', 'Arkansas'), ('NC', 'North Carolina'), ('VA', 'Virginia'), ('SD', 'South Dakota'), ('DC', 'District of Columbia'), ('NY', 'New York'), ('PA', 'Pennsylvania'), ('CO', 'Colorado'), ('MI', 'Michigan'), ('WI', 'Wisconsin'), ('VI', 'U.S. Virgin Islands'), ('HI', 'Hawaii'), ('LA', 'Louisiana'), ('FL', 'Florida'), ('AK', 'Alaska'), ('NE', 'Nebraska'), ('OH', 'Ohio'), ('SC', 'South Carolina'), ('TN', 'Tennessee'), ('VT', 'Vermont'), ('MD', 'Maryland'), ('TX', 'Texas'), ('UM', 'United States Minor Outlying Islands'), ('MO', 'Missouri'), ('OR', 'Oregon'), ('WY', 'Wyoming'), ('MT', 'Montana'), ('WA', 'Washington'), ('IN', 'Indiana'), ('ID', 'Idaho'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('RI', 'Rhode Island'), ('IL', 'Illinois'), ('NM', 'New Mexico'), ('MS', 'Mississippi'), ('WV', 'West Virginia'), ('ME', 'Maine'), ('DE', 'Delaware'), ('IA', 'Iowa'), ('ND', 'North Dakota')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
    ]
