# Generated by Django 4.2 on 2023-05-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0004_alter_client_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('MA', 'Massachusetts'), ('AS', 'American Samoa'), ('DE', 'Delaware'), ('WA', 'Washington'), ('WI', 'Wisconsin'), ('UM', 'United States Minor Outlying Islands'), ('HI', 'Hawaii'), ('WY', 'Wyoming'), ('DC', 'District of Columbia'), ('MN', 'Minnesota'), ('TN', 'Tennessee'), ('CO', 'Colorado'), ('NH', 'New Hampshire'), ('CA', 'California'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('WV', 'West Virginia'), ('MS', 'Mississippi'), ('NJ', 'New Jersey'), ('VA', 'Virginia'), ('NV', 'Nevada'), ('GA', 'Georgia'), ('NC', 'North Carolina'), ('AL', 'Alabama'), ('NY', 'New York'), ('ND', 'North Dakota'), ('AK', 'Alaska'), ('MI', 'Michigan'), ('FL', 'Florida'), ('MO', 'Missouri'), ('ID', 'Idaho'), ('AZ', 'Arizona'), ('TX', 'Texas'), ('NE', 'Nebraska'), ('ME', 'Maine'), ('AR', 'Arkansas'), ('GU', 'Guam'), ('IA', 'Iowa'), ('UT', 'Utah'), ('PR', 'Puerto Rico'), ('PA', 'Pennsylvania'), ('MD', 'Maryland'), ('CT', 'Connecticut'), ('IL', 'Illinois'), ('MT', 'Montana'), ('SD', 'South Dakota'), ('OK', 'Oklahoma'), ('OH', 'Ohio'), ('NM', 'New Mexico'), ('LA', 'Louisiana'), ('OR', 'Oregon'), ('IN', 'Indiana'), ('VT', 'Vermont'), ('RI', 'Rhode Island'), ('VI', 'U.S. Virgin Islands'), ('MP', 'Northern Mariana Islands'), ('SC', 'South Carolina')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='system',
            name='environment',
            field=models.CharField(blank=True, choices=[('On-Premises', 'On-Premises'), ('Cloud-Based', 'Cloud-Based'), ('Hybrid', 'Hybrid')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='fedramp_compliance_status',
            field=models.CharField(blank=True, choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Authorized', 'Authorized')], default='not_started', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='operational_status',
            field=models.CharField(blank=True, choices=[('Under Development', 'Under Development'), ('Operational', 'Operational'), ('Decommissioned', 'Decommissioned')], max_length=20, null=True),
        ),
    ]
