# Generated by Django 4.2 on 2023-05-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0006_alter_client_state_controlimplementation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('IN', 'Indiana'), ('OK', 'Oklahoma'), ('ID', 'Idaho'), ('KY', 'Kentucky'), ('NE', 'Nebraska'), ('TX', 'Texas'), ('IA', 'Iowa'), ('FL', 'Florida'), ('CA', 'California'), ('VI', 'U.S. Virgin Islands'), ('NY', 'New York'), ('NV', 'Nevada'), ('WA', 'Washington'), ('MP', 'Northern Mariana Islands'), ('WV', 'West Virginia'), ('MI', 'Michigan'), ('PR', 'Puerto Rico'), ('GU', 'Guam'), ('CO', 'Colorado'), ('NJ', 'New Jersey'), ('GA', 'Georgia'), ('IL', 'Illinois'), ('UT', 'Utah'), ('KS', 'Kansas'), ('ME', 'Maine'), ('MO', 'Missouri'), ('MD', 'Maryland'), ('OH', 'Ohio'), ('RI', 'Rhode Island'), ('UM', 'United States Minor Outlying Islands'), ('AR', 'Arkansas'), ('DC', 'District of Columbia'), ('MS', 'Mississippi'), ('LA', 'Louisiana'), ('AL', 'Alabama'), ('MA', 'Massachusetts'), ('ND', 'North Dakota'), ('SC', 'South Carolina'), ('TN', 'Tennessee'), ('NC', 'North Carolina'), ('VT', 'Vermont'), ('AS', 'American Samoa'), ('WI', 'Wisconsin'), ('MN', 'Minnesota'), ('NM', 'New Mexico'), ('AZ', 'Arizona'), ('DE', 'Delaware'), ('VA', 'Virginia'), ('CT', 'Connecticut'), ('SD', 'South Dakota'), ('MT', 'Montana'), ('OR', 'Oregon'), ('AK', 'Alaska'), ('PA', 'Pennsylvania'), ('NH', 'New Hampshire'), ('WY', 'Wyoming'), ('HI', 'Hawaii')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
    ]
