# Generated by Django 4.2 on 2023-05-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0007_alter_client_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlimplementation',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('LA', 'Louisiana'), ('CT', 'Connecticut'), ('ME', 'Maine'), ('OH', 'Ohio'), ('NH', 'New Hampshire'), ('VI', 'U.S. Virgin Islands'), ('WI', 'Wisconsin'), ('MN', 'Minnesota'), ('GA', 'Georgia'), ('UM', 'United States Minor Outlying Islands'), ('ID', 'Idaho'), ('PA', 'Pennsylvania'), ('AR', 'Arkansas'), ('AS', 'American Samoa'), ('UT', 'Utah'), ('WA', 'Washington'), ('SD', 'South Dakota'), ('AL', 'Alabama'), ('KY', 'Kentucky'), ('AZ', 'Arizona'), ('NE', 'Nebraska'), ('DC', 'District of Columbia'), ('WY', 'Wyoming'), ('WV', 'West Virginia'), ('CA', 'California'), ('IA', 'Iowa'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('IL', 'Illinois'), ('NY', 'New York'), ('ND', 'North Dakota'), ('MO', 'Missouri'), ('CO', 'Colorado'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('SC', 'South Carolina'), ('HI', 'Hawaii'), ('MI', 'Michigan'), ('NV', 'Nevada'), ('MP', 'Northern Mariana Islands'), ('NJ', 'New Jersey'), ('NC', 'North Carolina'), ('AK', 'Alaska'), ('OK', 'Oklahoma'), ('GU', 'Guam'), ('DE', 'Delaware'), ('RI', 'Rhode Island'), ('PR', 'Puerto Rico'), ('NM', 'New Mexico'), ('OR', 'Oregon'), ('MD', 'Maryland'), ('FL', 'Florida'), ('MS', 'Mississippi'), ('KS', 'Kansas'), ('MT', 'Montana'), ('IN', 'Indiana'), ('MA', 'Massachusetts')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
    ]
