# Generated by Django 4.2 on 2023-05-29 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0010_controlorigination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlimplementation',
            name='responsible_role',
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('WI', 'Wisconsin'), ('SC', 'South Carolina'), ('DE', 'Delaware'), ('AR', 'Arkansas'), ('DC', 'District of Columbia'), ('ND', 'North Dakota'), ('RI', 'Rhode Island'), ('TN', 'Tennessee'), ('VI', 'U.S. Virgin Islands'), ('MA', 'Massachusetts'), ('PR', 'Puerto Rico'), ('LA', 'Louisiana'), ('WY', 'Wyoming'), ('NC', 'North Carolina'), ('GU', 'Guam'), ('UM', 'United States Minor Outlying Islands'), ('CO', 'Colorado'), ('NY', 'New York'), ('FL', 'Florida'), ('SD', 'South Dakota'), ('IN', 'Indiana'), ('NM', 'New Mexico'), ('HI', 'Hawaii'), ('MT', 'Montana'), ('IA', 'Iowa'), ('ME', 'Maine'), ('OR', 'Oregon'), ('TX', 'Texas'), ('MS', 'Mississippi'), ('VT', 'Vermont'), ('ID', 'Idaho'), ('AZ', 'Arizona'), ('NE', 'Nebraska'), ('OK', 'Oklahoma'), ('IL', 'Illinois'), ('MI', 'Michigan'), ('WA', 'Washington'), ('MD', 'Maryland'), ('MP', 'Northern Mariana Islands'), ('GA', 'Georgia'), ('UT', 'Utah'), ('MN', 'Minnesota'), ('OH', 'Ohio'), ('CT', 'Connecticut'), ('MO', 'Missouri'), ('WV', 'West Virginia'), ('NH', 'New Hampshire'), ('CA', 'California'), ('PA', 'Pennsylvania'), ('AS', 'American Samoa'), ('NV', 'Nevada'), ('KY', 'Kentucky'), ('VA', 'Virginia'), ('NJ', 'New Jersey'), ('KS', 'Kansas'), ('AK', 'Alaska'), ('AL', 'Alabama')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
    ]
