# Generated by Django 4.2 on 2023-05-29 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0011_remove_controlimplementation_responsible_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsibleRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible_role', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Responsible Role',
                'verbose_name_plural': 'Responsible Roles',
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('PA', 'Pennsylvania'), ('KY', 'Kentucky'), ('NM', 'New Mexico'), ('OH', 'Ohio'), ('RI', 'Rhode Island'), ('IN', 'Indiana'), ('OR', 'Oregon'), ('IA', 'Iowa'), ('NY', 'New York'), ('PR', 'Puerto Rico'), ('IL', 'Illinois'), ('DE', 'Delaware'), ('CA', 'California'), ('MD', 'Maryland'), ('MS', 'Mississippi'), ('AL', 'Alabama'), ('AR', 'Arkansas'), ('HI', 'Hawaii'), ('VT', 'Vermont'), ('MT', 'Montana'), ('UT', 'Utah'), ('ND', 'North Dakota'), ('TN', 'Tennessee'), ('FL', 'Florida'), ('KS', 'Kansas'), ('AK', 'Alaska'), ('MN', 'Minnesota'), ('VA', 'Virginia'), ('GA', 'Georgia'), ('MI', 'Michigan'), ('SC', 'South Carolina'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('MO', 'Missouri'), ('MP', 'Northern Mariana Islands'), ('UM', 'United States Minor Outlying Islands'), ('OK', 'Oklahoma'), ('CO', 'Colorado'), ('ME', 'Maine'), ('MA', 'Massachusetts'), ('NV', 'Nevada'), ('WA', 'Washington'), ('DC', 'District of Columbia'), ('NC', 'North Carolina'), ('TX', 'Texas'), ('WY', 'Wyoming'), ('GU', 'Guam'), ('AZ', 'Arizona'), ('ID', 'Idaho'), ('AS', 'American Samoa'), ('NE', 'Nebraska'), ('NJ', 'New Jersey'), ('NH', 'New Hampshire'), ('LA', 'Louisiana'), ('CT', 'Connecticut'), ('VI', 'U.S. Virgin Islands'), ('SD', 'South Dakota')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='controlimplementation',
            name='responsible_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AlchemyApp.responsiblerole'),
        ),
    ]
