# Generated by Django 4.2 on 2023-05-29 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0012_responsiblerole_alter_client_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('CT', 'Connecticut'), ('IL', 'Illinois'), ('UM', 'United States Minor Outlying Islands'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('MO', 'Missouri'), ('GA', 'Georgia'), ('TN', 'Tennessee'), ('IN', 'Indiana'), ('RI', 'Rhode Island'), ('OK', 'Oklahoma'), ('WI', 'Wisconsin'), ('AL', 'Alabama'), ('OH', 'Ohio'), ('AR', 'Arkansas'), ('OR', 'Oregon'), ('NM', 'New Mexico'), ('TX', 'Texas'), ('WV', 'West Virginia'), ('ID', 'Idaho'), ('NE', 'Nebraska'), ('NC', 'North Carolina'), ('SD', 'South Dakota'), ('WA', 'Washington'), ('KY', 'Kentucky'), ('MS', 'Mississippi'), ('MA', 'Massachusetts'), ('LA', 'Louisiana'), ('SC', 'South Carolina'), ('VI', 'U.S. Virgin Islands'), ('UT', 'Utah'), ('MT', 'Montana'), ('DE', 'Delaware'), ('IA', 'Iowa'), ('ME', 'Maine'), ('MP', 'Northern Mariana Islands'), ('HI', 'Hawaii'), ('KS', 'Kansas'), ('MN', 'Minnesota'), ('WY', 'Wyoming'), ('MI', 'Michigan'), ('NJ', 'New Jersey'), ('VT', 'Vermont'), ('NV', 'Nevada'), ('ND', 'North Dakota'), ('PA', 'Pennsylvania'), ('FL', 'Florida'), ('CO', 'Colorado'), ('CA', 'California'), ('MD', 'Maryland'), ('PR', 'Puerto Rico'), ('DC', 'District of Columbia'), ('NH', 'New Hampshire'), ('VA', 'Virginia'), ('GU', 'Guam'), ('NY', 'New York'), ('AS', 'American Samoa')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='controlimplementation',
            name='responsible_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='AlchemyApp.responsiblerole'),
        ),
        migrations.CreateModel(
            name='NISTControlPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_letter', models.CharField(max_length=1)),
                ('part_description', models.TextField()),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='AlchemyApp.nistcontrol')),
            ],
            options={
                'verbose_name': 'NIST Control Part',
                'verbose_name_plural': 'NIST Control Parts',
            },
        ),
    ]
