# Generated by Django 4.2 on 2023-05-30 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0013_alter_client_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlimplementation',
            name='statement',
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('WV', 'West Virginia'), ('ND', 'North Dakota'), ('MI', 'Michigan'), ('IA', 'Iowa'), ('VI', 'U.S. Virgin Islands'), ('PA', 'Pennsylvania'), ('OR', 'Oregon'), ('DC', 'District of Columbia'), ('CA', 'California'), ('DE', 'Delaware'), ('NE', 'Nebraska'), ('AL', 'Alabama'), ('NV', 'Nevada'), ('OH', 'Ohio'), ('SC', 'South Carolina'), ('HI', 'Hawaii'), ('LA', 'Louisiana'), ('MT', 'Montana'), ('NJ', 'New Jersey'), ('SD', 'South Dakota'), ('MS', 'Mississippi'), ('VT', 'Vermont'), ('WY', 'Wyoming'), ('WA', 'Washington'), ('ID', 'Idaho'), ('OK', 'Oklahoma'), ('MP', 'Northern Mariana Islands'), ('MN', 'Minnesota'), ('GA', 'Georgia'), ('NM', 'New Mexico'), ('TX', 'Texas'), ('AK', 'Alaska'), ('NY', 'New York'), ('CT', 'Connecticut'), ('CO', 'Colorado'), ('IN', 'Indiana'), ('ME', 'Maine'), ('MO', 'Missouri'), ('RI', 'Rhode Island'), ('AS', 'American Samoa'), ('NC', 'North Carolina'), ('KY', 'Kentucky'), ('AZ', 'Arizona'), ('WI', 'Wisconsin'), ('AR', 'Arkansas'), ('KS', 'Kansas'), ('MA', 'Massachusetts'), ('IL', 'Illinois'), ('PR', 'Puerto Rico'), ('UM', 'United States Minor Outlying Islands'), ('VA', 'Virginia'), ('MD', 'Maryland'), ('NH', 'New Hampshire'), ('GU', 'Guam'), ('FL', 'Florida'), ('UT', 'Utah'), ('TN', 'Tennessee')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
        migrations.CreateModel(
            name='ControlImplementationStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('control_implementation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_statement_parts', to='AlchemyApp.controlimplementation')),
                ('control_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlchemyApp.nistcontrolpart')),
            ],
            options={
                'unique_together': {('control_implementation', 'control_part')},
            },
        ),
    ]
