# Generated by Django 4.2 on 2023-05-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0014_remove_controlimplementation_statement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('RI', 'Rhode Island'), ('AR', 'Arkansas'), ('TX', 'Texas'), ('WV', 'West Virginia'), ('DC', 'District of Columbia'), ('TN', 'Tennessee'), ('NE', 'Nebraska'), ('KY', 'Kentucky'), ('NY', 'New York'), ('HI', 'Hawaii'), ('WY', 'Wyoming'), ('PR', 'Puerto Rico'), ('KS', 'Kansas'), ('MO', 'Missouri'), ('NV', 'Nevada'), ('ND', 'North Dakota'), ('GA', 'Georgia'), ('NJ', 'New Jersey'), ('OK', 'Oklahoma'), ('OH', 'Ohio'), ('AS', 'American Samoa'), ('CO', 'Colorado'), ('CA', 'California'), ('UM', 'United States Minor Outlying Islands'), ('AL', 'Alabama'), ('NM', 'New Mexico'), ('FL', 'Florida'), ('MI', 'Michigan'), ('MD', 'Maryland'), ('ID', 'Idaho'), ('VA', 'Virginia'), ('OR', 'Oregon'), ('AK', 'Alaska'), ('WI', 'Wisconsin'), ('AZ', 'Arizona'), ('MP', 'Northern Mariana Islands'), ('DE', 'Delaware'), ('IL', 'Illinois'), ('SC', 'South Carolina'), ('VT', 'Vermont'), ('SD', 'South Dakota'), ('MN', 'Minnesota'), ('CT', 'Connecticut'), ('MA', 'Massachusetts'), ('NH', 'New Hampshire'), ('ME', 'Maine'), ('WA', 'Washington'), ('IA', 'Iowa'), ('NC', 'North Carolina'), ('GU', 'Guam'), ('VI', 'U.S. Virgin Islands'), ('IN', 'Indiana'), ('PA', 'Pennsylvania'), ('LA', 'Louisiana'), ('MS', 'Mississippi'), ('UT', 'Utah'), ('MT', 'Montana')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
    ]
