# Generated by Django 4.2 on 2023-06-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0019_controlimplementation_statement_alter_client_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('AK', 'Alaska'), ('VT', 'Vermont'), ('DC', 'District of Columbia'), ('MO', 'Missouri'), ('GU', 'Guam'), ('NC', 'North Carolina'), ('WI', 'Wisconsin'), ('MI', 'Michigan'), ('TN', 'Tennessee'), ('KS', 'Kansas'), ('LA', 'Louisiana'), ('OH', 'Ohio'), ('TX', 'Texas'), ('WA', 'Washington'), ('MD', 'Maryland'), ('NV', 'Nevada'), ('MN', 'Minnesota'), ('VA', 'Virginia'), ('SC', 'South Carolina'), ('CO', 'Colorado'), ('CA', 'California'), ('NJ', 'New Jersey'), ('NY', 'New York'), ('IA', 'Iowa'), ('RI', 'Rhode Island'), ('IL', 'Illinois'), ('NM', 'New Mexico'), ('VI', 'U.S. Virgin Islands'), ('PA', 'Pennsylvania'), ('OR', 'Oregon'), ('MS', 'Mississippi'), ('NH', 'New Hampshire'), ('NE', 'Nebraska'), ('ND', 'North Dakota'), ('AL', 'Alabama'), ('PR', 'Puerto Rico'), ('AS', 'American Samoa'), ('UT', 'Utah'), ('WV', 'West Virginia'), ('MP', 'Northern Mariana Islands'), ('KY', 'Kentucky'), ('OK', 'Oklahoma'), ('MT', 'Montana'), ('GA', 'Georgia'), ('FL', 'Florida'), ('SD', 'South Dakota'), ('MA', 'Massachusetts'), ('AZ', 'Arizona'), ('CT', 'Connecticut'), ('IN', 'Indiana'), ('HI', 'Hawaii'), ('WY', 'Wyoming'), ('UM', 'United States Minor Outlying Islands'), ('DE', 'Delaware'), ('AR', 'Arkansas'), ('ME', 'Maine'), ('ID', 'Idaho')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
    ]
