# Generated by Django 4.2 on 2023-06-22 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0024_alter_client_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('IL', 'Illinois'), ('NY', 'New York'), ('MT', 'Montana'), ('SC', 'South Carolina'), ('CO', 'Colorado'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('VT', 'Vermont'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('RI', 'Rhode Island'), ('MP', 'Northern Mariana Islands'), ('WV', 'West Virginia'), ('AK', 'Alaska'), ('KY', 'Kentucky'), ('WY', 'Wyoming'), ('AL', 'Alabama'), ('NM', 'New Mexico'), ('UM', 'United States Minor Outlying Islands'), ('VI', 'U.S. Virgin Islands'), ('ID', 'Idaho'), ('MI', 'Michigan'), ('NJ', 'New Jersey'), ('NC', 'North Carolina'), ('AR', 'Arkansas'), ('IA', 'Iowa'), ('OR', 'Oregon'), ('NH', 'New Hampshire'), ('MN', 'Minnesota'), ('MO', 'Missouri'), ('NV', 'Nevada'), ('GU', 'Guam'), ('TN', 'Tennessee'), ('AZ', 'Arizona'), ('OK', 'Oklahoma'), ('UT', 'Utah'), ('CA', 'California'), ('WI', 'Wisconsin'), ('GA', 'Georgia'), ('AS', 'American Samoa'), ('DE', 'Delaware'), ('LA', 'Louisiana'), ('PR', 'Puerto Rico'), ('TX', 'Texas'), ('SD', 'South Dakota'), ('MS', 'Mississippi'), ('IN', 'Indiana'), ('CT', 'Connecticut'), ('KS', 'Kansas'), ('WA', 'Washington'), ('VA', 'Virginia'), ('MD', 'Maryland'), ('HI', 'Hawaii'), ('MA', 'Massachusetts'), ('NE', 'Nebraska'), ('PA', 'Pennsylvania'), ('ME', 'Maine')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='controlimplementation',
            name='control_family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_implementations', to='AlchemyApp.controlfamily'),
        ),
    ]
