# Generated by Django 4.2 on 2023-06-26 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0025_alter_client_state_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlfamily',
            options={'ordering': ['family_abbreviation'], 'verbose_name': 'Control Family', 'verbose_name_plural': 'Control Families'},
        ),
        migrations.AlterModelOptions(
            name='controlimplementation',
            options={'ordering': ['control__control_family__family_abbreviation', 'control__control_number', 'control__control_enhancement']},
        ),
        migrations.AlterModelOptions(
            name='nistcontrolpart',
            options={'ordering': ['part_letter'], 'verbose_name': 'NIST Control Part', 'verbose_name_plural': 'NIST Control Parts'},
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('GU', 'Guam'), ('SD', 'South Dakota'), ('IA', 'Iowa'), ('DE', 'Delaware'), ('ME', 'Maine'), ('NJ', 'New Jersey'), ('MO', 'Missouri'), ('WA', 'Washington'), ('WI', 'Wisconsin'), ('IN', 'Indiana'), ('VT', 'Vermont'), ('LA', 'Louisiana'), ('AL', 'Alabama'), ('AS', 'American Samoa'), ('TX', 'Texas'), ('NM', 'New Mexico'), ('NY', 'New York'), ('CA', 'California'), ('AR', 'Arkansas'), ('KS', 'Kansas'), ('AK', 'Alaska'), ('GA', 'Georgia'), ('NH', 'New Hampshire'), ('MS', 'Mississippi'), ('UT', 'Utah'), ('NE', 'Nebraska'), ('CT', 'Connecticut'), ('OR', 'Oregon'), ('KY', 'Kentucky'), ('ID', 'Idaho'), ('NV', 'Nevada'), ('UM', 'United States Minor Outlying Islands'), ('CO', 'Colorado'), ('ND', 'North Dakota'), ('OK', 'Oklahoma'), ('WV', 'West Virginia'), ('AZ', 'Arizona'), ('NC', 'North Carolina'), ('OH', 'Ohio'), ('MN', 'Minnesota'), ('VI', 'U.S. Virgin Islands'), ('VA', 'Virginia'), ('SC', 'South Carolina'), ('RI', 'Rhode Island'), ('FL', 'Florida'), ('PR', 'Puerto Rico'), ('MA', 'Massachusetts'), ('TN', 'Tennessee'), ('WY', 'Wyoming'), ('HI', 'Hawaii'), ('MI', 'Michigan'), ('PA', 'Pennsylvania'), ('MT', 'Montana'), ('DC', 'District of Columbia'), ('MD', 'Maryland'), ('IL', 'Illinois'), ('MP', 'Northern Mariana Islands')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='controlimplementation',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_implementations', to='AlchemyApp.system'),
        ),
    ]
