# Generated by Django 4.2 on 2023-06-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0027_alter_client_state_fedrampparameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('WY', 'Wyoming'), ('WV', 'West Virginia'), ('AZ', 'Arizona'), ('CA', 'California'), ('TX', 'Texas'), ('DE', 'Delaware'), ('GU', 'Guam'), ('WI', 'Wisconsin'), ('PR', 'Puerto Rico'), ('UM', 'United States Minor Outlying Islands'), ('CT', 'Connecticut'), ('NH', 'New Hampshire'), ('MN', 'Minnesota'), ('NJ', 'New Jersey'), ('WA', 'Washington'), ('ND', 'North Dakota'), ('ID', 'Idaho'), ('KY', 'Kentucky'), ('MD', 'Maryland'), ('VT', 'Vermont'), ('SD', 'South Dakota'), ('AR', 'Arkansas'), ('RI', 'Rhode Island'), ('ME', 'Maine'), ('MI', 'Michigan'), ('OK', 'Oklahoma'), ('IN', 'Indiana'), ('AK', 'Alaska'), ('MT', 'Montana'), ('NC', 'North Carolina'), ('NM', 'New Mexico'), ('NV', 'Nevada'), ('SC', 'South Carolina'), ('VA', 'Virginia'), ('OR', 'Oregon'), ('AS', 'American Samoa'), ('FL', 'Florida'), ('KS', 'Kansas'), ('LA', 'Louisiana'), ('MP', 'Northern Mariana Islands'), ('MO', 'Missouri'), ('HI', 'Hawaii'), ('OH', 'Ohio'), ('MA', 'Massachusetts'), ('CO', 'Colorado'), ('GA', 'Georgia'), ('IA', 'Iowa'), ('NY', 'New York'), ('TN', 'Tennessee'), ('MS', 'Mississippi'), ('PA', 'Pennsylvania'), ('UT', 'Utah'), ('DC', 'District of Columbia'), ('AL', 'Alabama'), ('VI', 'U.S. Virgin Islands'), ('IL', 'Illinois'), ('NE', 'Nebraska')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
    ]
