# Generated by Django 4.2 on 2023-07-06 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0031_remove_fedrampparameter_part_alter_client_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlimplementationstatement',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='controlimplementationstatement',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_statements', to='AlchemyApp.controlimplementationstatement'),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('GU', 'Guam'), ('PR', 'Puerto Rico'), ('CT', 'Connecticut'), ('SC', 'South Carolina'), ('RI', 'Rhode Island'), ('AS', 'American Samoa'), ('KS', 'Kansas'), ('WA', 'Washington'), ('AL', 'Alabama'), ('MN', 'Minnesota'), ('MT', 'Montana'), ('NC', 'North Carolina'), ('KY', 'Kentucky'), ('HI', 'Hawaii'), ('NJ', 'New Jersey'), ('AK', 'Alaska'), ('LA', 'Louisiana'), ('DC', 'District of Columbia'), ('ND', 'North Dakota'), ('DE', 'Delaware'), ('NM', 'New Mexico'), ('TX', 'Texas'), ('TN', 'Tennessee'), ('FL', 'Florida'), ('VI', 'U.S. Virgin Islands'), ('IN', 'Indiana'), ('ME', 'Maine'), ('AR', 'Arkansas'), ('NY', 'New York'), ('NH', 'New Hampshire'), ('SD', 'South Dakota'), ('CA', 'California'), ('ID', 'Idaho'), ('GA', 'Georgia'), ('WI', 'Wisconsin'), ('NE', 'Nebraska'), ('VA', 'Virginia'), ('VT', 'Vermont'), ('NV', 'Nevada'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('AZ', 'Arizona'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('CO', 'Colorado'), ('OH', 'Ohio'), ('WV', 'West Virginia'), ('WY', 'Wyoming'), ('UT', 'Utah'), ('IL', 'Illinois'), ('PA', 'Pennsylvania'), ('MP', 'Northern Mariana Islands'), ('IA', 'Iowa'), ('UM', 'United States Minor Outlying Islands'), ('MO', 'Missouri'), ('MS', 'Mississippi'), ('MD', 'Maryland')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='controlimplementationstatement',
            name='control_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlchemyApp.nistcontrolelement'),
        ),
        migrations.AlterField(
            model_name='controlimplementationstatement',
            name='control_implementation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_statement_elements', to='AlchemyApp.controlimplementation'),
        ),
    ]
