# Generated by Django 4.2 on 2023-07-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0032_controlimplementationstatement_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('GU', 'Guam'), ('NY', 'New York'), ('AK', 'Alaska'), ('SC', 'South Carolina'), ('NH', 'New Hampshire'), ('CO', 'Colorado'), ('AL', 'Alabama'), ('DE', 'Delaware'), ('RI', 'Rhode Island'), ('PR', 'Puerto Rico'), ('MI', 'Michigan'), ('GA', 'Georgia'), ('TN', 'Tennessee'), ('KY', 'Kentucky'), ('WY', 'Wyoming'), ('NC', 'North Carolina'), ('ID', 'Idaho'), ('IN', 'Indiana'), ('WA', 'Washington'), ('SD', 'South Dakota'), ('MN', 'Minnesota'), ('ND', 'North Dakota'), ('AR', 'Arkansas'), ('NM', 'New Mexico'), ('AZ', 'Arizona'), ('DC', 'District of Columbia'), ('MA', 'Massachusetts'), ('VT', 'Vermont'), ('PA', 'Pennsylvania'), ('NJ', 'New Jersey'), ('LA', 'Louisiana'), ('CT', 'Connecticut'), ('VA', 'Virginia'), ('CA', 'California'), ('NE', 'Nebraska'), ('WV', 'West Virginia'), ('MO', 'Missouri'), ('VI', 'U.S. Virgin Islands'), ('MT', 'Montana'), ('AS', 'American Samoa'), ('OK', 'Oklahoma'), ('MP', 'Northern Mariana Islands'), ('UT', 'Utah'), ('HI', 'Hawaii'), ('KS', 'Kansas'), ('MD', 'Maryland'), ('MS', 'Mississippi'), ('NV', 'Nevada'), ('IL', 'Illinois'), ('WI', 'Wisconsin'), ('UM', 'United States Minor Outlying Islands'), ('TX', 'Texas'), ('FL', 'Florida'), ('ME', 'Maine'), ('OH', 'Ohio'), ('IA', 'Iowa'), ('OR', 'Oregon')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
    ]
