# Generated by Django 4.2 on 2023-07-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0035_alter_client_state_alter_fedrampparameter_control_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('LA', 'Louisiana'), ('HI', 'Hawaii'), ('MA', 'Massachusetts'), ('VT', 'Vermont'), ('IL', 'Illinois'), ('IA', 'Iowa'), ('TX', 'Texas'), ('VI', 'U.S. Virgin Islands'), ('NV', 'Nevada'), ('PA', 'Pennsylvania'), ('KS', 'Kansas'), ('MP', 'Northern Mariana Islands'), ('ND', 'North Dakota'), ('MS', 'Mississippi'), ('CO', 'Colorado'), ('ID', 'Idaho'), ('RI', 'Rhode Island'), ('GA', 'Georgia'), ('OR', 'Oregon'), ('AS', 'American Samoa'), ('MD', 'Maryland'), ('NY', 'New York'), ('SD', 'South Dakota'), ('GU', 'Guam'), ('AL', 'Alabama'), ('MN', 'Minnesota'), ('UT', 'Utah'), ('FL', 'Florida'), ('WA', 'Washington'), ('PR', 'Puerto Rico'), ('OK', 'Oklahoma'), ('AZ', 'Arizona'), ('TN', 'Tennessee'), ('NH', 'New Hampshire'), ('CA', 'California'), ('AR', 'Arkansas'), ('MT', 'Montana'), ('WI', 'Wisconsin'), ('CT', 'Connecticut'), ('NM', 'New Mexico'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('AK', 'Alaska'), ('WV', 'West Virginia'), ('NC', 'North Carolina'), ('ME', 'Maine'), ('MI', 'Michigan'), ('IN', 'Indiana'), ('SC', 'South Carolina'), ('UM', 'United States Minor Outlying Islands'), ('OH', 'Ohio'), ('KY', 'Kentucky'), ('NE', 'Nebraska'), ('WY', 'Wyoming'), ('MO', 'Missouri'), ('VA', 'Virginia'), ('NJ', 'New Jersey')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
    ]
