# Generated by Django 4.2 on 2023-07-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0036_alter_client_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='service_model',
            field=models.CharField(blank=True, choices=[('Infrastructure as a Service (IaaS)', 'Infrastructure as a Service (IaaS)'), ('Platform as a Service (PaaS)', 'Platform as a Service (PaaS)'), ('Software as a Service (SaaS)', 'Software as a Service (SaaS)'), ('Low-Impact Software as a Service (LI-SaaS)', 'Low-Impact Software as a Service (LI-SaaS)')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('MN', 'Minnesota'), ('PA', 'Pennsylvania'), ('SC', 'South Carolina'), ('NE', 'Nebraska'), ('HI', 'Hawaii'), ('MD', 'Maryland'), ('AK', 'Alaska'), ('KY', 'Kentucky'), ('AR', 'Arkansas'), ('CO', 'Colorado'), ('MA', 'Massachusetts'), ('GA', 'Georgia'), ('MS', 'Mississippi'), ('CT', 'Connecticut'), ('NH', 'New Hampshire'), ('NC', 'North Carolina'), ('MP', 'Northern Mariana Islands'), ('PR', 'Puerto Rico'), ('WI', 'Wisconsin'), ('IA', 'Iowa'), ('TX', 'Texas'), ('UM', 'United States Minor Outlying Islands'), ('SD', 'South Dakota'), ('CA', 'California'), ('ID', 'Idaho'), ('NM', 'New Mexico'), ('WA', 'Washington'), ('OR', 'Oregon'), ('LA', 'Louisiana'), ('IN', 'Indiana'), ('IL', 'Illinois'), ('NV', 'Nevada'), ('NJ', 'New Jersey'), ('VT', 'Vermont'), ('ME', 'Maine'), ('VI', 'U.S. Virgin Islands'), ('AZ', 'Arizona'), ('MI', 'Michigan'), ('TN', 'Tennessee'), ('NY', 'New York'), ('ND', 'North Dakota'), ('GU', 'Guam'), ('OK', 'Oklahoma'), ('FL', 'Florida'), ('WY', 'Wyoming'), ('AL', 'Alabama'), ('VA', 'Virginia'), ('AS', 'American Samoa'), ('MT', 'Montana'), ('UT', 'Utah'), ('RI', 'Rhode Island'), ('MO', 'Missouri'), ('DE', 'Delaware'), ('OH', 'Ohio'), ('DC', 'District of Columbia'), ('KS', 'Kansas'), ('WV', 'West Virginia')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='system',
            name='fedramp_compliance_status',
            field=models.CharField(blank=True, choices=[('Not Started', 'Not Started'), ('In Process', 'In Process'), ('Authorized', 'Authorized')], default='Not Started', max_length=20, null=True),
        ),
    ]
