# Generated by Django 4.2 on 2023-07-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0038_system_impact_level_alter_client_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('WY', 'Wyoming'), ('AL', 'Alabama'), ('NY', 'New York'), ('GA', 'Georgia'), ('CA', 'California'), ('SD', 'South Dakota'), ('DE', 'Delaware'), ('NM', 'New Mexico'), ('NE', 'Nebraska'), ('NC', 'North Carolina'), ('MA', 'Massachusetts'), ('UT', 'Utah'), ('VA', 'Virginia'), ('NJ', 'New Jersey'), ('UM', 'United States Minor Outlying Islands'), ('GU', 'Guam'), ('MP', 'Northern Mariana Islands'), ('MD', 'Maryland'), ('MI', 'Michigan'), ('IA', 'Iowa'), ('OR', 'Oregon'), ('IN', 'Indiana'), ('TN', 'Tennessee'), ('WA', 'Washington'), ('NV', 'Nevada'), ('OH', 'Ohio'), ('WV', 'West Virginia'), ('ME', 'Maine'), ('IL', 'Illinois'), ('CO', 'Colorado'), ('DC', 'District of Columbia'), ('MO', 'Missouri'), ('AZ', 'Arizona'), ('KS', 'Kansas'), ('ND', 'North Dakota'), ('SC', 'South Carolina'), ('TX', 'Texas'), ('ID', 'Idaho'), ('HI', 'Hawaii'), ('FL', 'Florida'), ('KY', 'Kentucky'), ('WI', 'Wisconsin'), ('PR', 'Puerto Rico'), ('VT', 'Vermont'), ('MS', 'Mississippi'), ('AK', 'Alaska'), ('AS', 'American Samoa'), ('LA', 'Louisiana'), ('PA', 'Pennsylvania'), ('MN', 'Minnesota'), ('RI', 'Rhode Island'), ('VI', 'U.S. Virgin Islands'), ('AR', 'Arkansas'), ('OK', 'Oklahoma'), ('MT', 'Montana'), ('CT', 'Connecticut'), ('NH', 'New Hampshire')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='system',
            name='impact_level',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High'), ('LI-Software as a Service (SaaS)', 'LI-Software as a Service (SaaS)')], max_length=36, null=True),
        ),
    ]
