# Generated by Django 4.2 on 2023-12-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0041_controlparameter_alter_client_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('WI', 'Wisconsin'), ('GA', 'Georgia'), ('PR', 'Puerto Rico'), ('MI', 'Michigan'), ('UT', 'Utah'), ('NY', 'New York'), ('GU', 'Guam'), ('MD', 'Maryland'), ('SC', 'South Carolina'), ('IN', 'Indiana'), ('HI', 'Hawaii'), ('KS', 'Kansas'), ('DC', 'District of Columbia'), ('PA', 'Pennsylvania'), ('TN', 'Tennessee'), ('MS', 'Mississippi'), ('NV', 'Nevada'), ('WA', 'Washington'), ('FL', 'Florida'), ('SD', 'South Dakota'), ('IL', 'Illinois'), ('MA', 'Massachusetts'), ('WY', 'Wyoming'), ('VI', 'U.S. Virgin Islands'), ('AR', 'Arkansas'), ('KY', 'Kentucky'), ('UM', 'United States Minor Outlying Islands'), ('LA', 'Louisiana'), ('IA', 'Iowa'), ('ME', 'Maine'), ('AS', 'American Samoa'), ('MP', 'Northern Mariana Islands'), ('CT', 'Connecticut'), ('NC', 'North Carolina'), ('VA', 'Virginia'), ('NJ', 'New Jersey'), ('DE', 'Delaware'), ('MO', 'Missouri'), ('CO', 'Colorado'), ('OH', 'Ohio'), ('NE', 'Nebraska'), ('OR', 'Oregon'), ('AL', 'Alabama'), ('ID', 'Idaho'), ('NM', 'New Mexico'), ('ND', 'North Dakota'), ('RI', 'Rhode Island'), ('AZ', 'Arizona'), ('MN', 'Minnesota'), ('TX', 'Texas'), ('MT', 'Montana'), ('AK', 'Alaska'), ('NH', 'New Hampshire'), ('WV', 'West Virginia'), ('CA', 'California'), ('OK', 'Oklahoma'), ('VT', 'Vermont')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
    ]
