# Generated by Django 4.2 on 2023-04-19 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlfamily',
            name='family_abbreviation',
            field=models.CharField(choices=[('AC', 'AC'), ('AT', 'AT'), ('AU', 'AU'), ('CM', 'CM'), ('CP', 'CP'), ('IA', 'IA'), ('IR', 'IR'), ('MA', 'MA'), ('MP', 'MP'), ('PE', 'PE'), ('PL', 'PL'), ('PS', 'PS'), ('RA', 'RA'), ('CA', 'CA'), ('SC', 'SC'), ('SI', 'SI'), ('SA', 'SA')], default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='controlfamily',
            name='family_description',
            field=models.CharField(blank='True', max_length=255, null='True'),
        ),
        migrations.AlterField(
            model_name='nistcontrol',
            name='control_family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlchemyApp.controlfamily'),
        ),
    ]
