# Generated by Django 4.2 on 2023-04-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0003_remove_nistcontrol_control_family_abbv'),
    ]

    operations = [
        migrations.AddField(
            model_name='nistcontrol',
            name='supplemental_guidance',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
