# Generated by Django 4.2 on 2023-05-10 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0005_alter_client_state_alter_system_environment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('NV', 'Nevada'), ('SC', 'South Carolina'), ('OR', 'Oregon'), ('VI', 'U.S. Virgin Islands'), ('OH', 'Ohio'), ('ND', 'North Dakota'), ('NJ', 'New Jersey'), ('TN', 'Tennessee'), ('DC', 'District of Columbia'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('IA', 'Iowa'), ('SD', 'South Dakota'), ('AS', 'American Samoa'), ('MD', 'Maryland'), ('CA', 'California'), ('AL', 'Alabama'), ('CO', 'Colorado'), ('HI', 'Hawaii'), ('IL', 'Illinois'), ('NC', 'North Carolina'), ('MT', 'Montana'), ('AK', 'Alaska'), ('KY', 'Kentucky'), ('AR', 'Arkansas'), ('MA', 'Massachusetts'), ('MO', 'Missouri'), ('NE', 'Nebraska'), ('WI', 'Wisconsin'), ('LA', 'Louisiana'), ('GU', 'Guam'), ('PR', 'Puerto Rico'), ('KS', 'Kansas'), ('TX', 'Texas'), ('FL', 'Florida'), ('NH', 'New Hampshire'), ('ME', 'Maine'), ('GA', 'Georgia'), ('WV', 'West Virginia'), ('NM', 'New Mexico'), ('UM', 'United States Minor Outlying Islands'), ('ID', 'Idaho'), ('AZ', 'Arizona'), ('CT', 'Connecticut'), ('RI', 'Rhode Island'), ('NY', 'New York'), ('MS', 'Mississippi'), ('VA', 'Virginia'), ('DE', 'Delaware'), ('WA', 'Washington'), ('MP', 'Northern Mariana Islands'), ('PA', 'Pennsylvania'), ('IN', 'Indiana'), ('WY', 'Wyoming'), ('VT', 'Vermont'), ('UT', 'Utah'), ('OK', 'Oklahoma')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
        migrations.CreateModel(
            name='ControlImplementation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible_role', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, choices=[('Implemented', 'Implemented'), ('Partially Implemented', 'Partially Implemented'), ('Planned', 'Planned'), ('Alternative Implementation', 'Alternative Implementation'), ('Not Applicable', 'Not Applicable')], max_length=30, null=True)),
                ('origination', models.CharField(blank=True, choices=[('Service Provider Corporate', 'Service Provider Corporate'), ('Service Provider System Specific', 'Service Provider System Specific'), ('Service Provider Hybrid', 'Service Provider Hybrid'), ('Configured by Customer', 'Configured by Customer'), ('Provided by Customer', 'Provided by Customer'), ('Shared', 'Shared'), ('Inherited', 'Inherited')], max_length=50, null=True)),
                ('statement', models.TextField(blank=True, null=True)),
                ('progress', models.CharField(blank=True, choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=30, null=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlchemyApp.nistcontrol')),
                ('control_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlchemyApp.controlfamily')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlchemyApp.system')),
            ],
        ),
    ]
