# Generated by Django 4.2 on 2023-04-26 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('AlchemyApp', '0005_informationcategory_informationsubcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informationcategory',
            options={'verbose_name': 'Information Category', 'verbose_name_plural': 'Information Categories'},
        ),
        migrations.AlterModelOptions(
            name='informationsubcategory',
            options={'verbose_name': 'Information Subcategory', 'verbose_name_plural': 'Information SubCategories'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='customuser_groups', related_query_name='customuser', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_user_permissions', related_query_name='customuser', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
