# Generated by Django 4.2 on 2023-04-30 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0006_alter_informationcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(default='placeholder', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_title', models.CharField(blank=True, max_length=255, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlchemyApp.client')),
                ('information_subcategories', models.ManyToManyField(blank=True, help_text='The information subcategories that flow through the system.', related_name='system_information_subcategories', related_query_name='system', to='AlchemyApp.informationsubcategory', verbose_name='information subcategories')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='answer',
            name='system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AlchemyApp.system'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('system', 'question')},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='client',
        ),
    ]
