# Generated by Django 4.2 on 2023-05-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0008_controlimplementation_last_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImplementationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Implemented', 'Implemented'), ('Partially Implemented', 'Partially Implemented'), ('Planned', 'Planned'), ('Alternative Implementation', 'Alternative Implementation'), ('Not Applicable', 'Not Applicable')], max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('HI', 'Hawaii'), ('AK', 'Alaska'), ('TN', 'Tennessee'), ('WY', 'Wyoming'), ('WA', 'Washington'), ('FL', 'Florida'), ('MI', 'Michigan'), ('DE', 'Delaware'), ('IL', 'Illinois'), ('SC', 'South Carolina'), ('NM', 'New Mexico'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('KY', 'Kentucky'), ('VA', 'Virginia'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('NC', 'North Carolina'), ('MO', 'Missouri'), ('CO', 'Colorado'), ('DC', 'District of Columbia'), ('NY', 'New York'), ('ND', 'North Dakota'), ('ID', 'Idaho'), ('MA', 'Massachusetts'), ('MP', 'Northern Mariana Islands'), ('MT', 'Montana'), ('NH', 'New Hampshire'), ('OH', 'Ohio'), ('SD', 'South Dakota'), ('NE', 'Nebraska'), ('OK', 'Oklahoma'), ('VT', 'Vermont'), ('AS', 'American Samoa'), ('OR', 'Oregon'), ('IN', 'Indiana'), ('WV', 'West Virginia'), ('PA', 'Pennsylvania'), ('WI', 'Wisconsin'), ('CT', 'Connecticut'), ('PR', 'Puerto Rico'), ('UM', 'United States Minor Outlying Islands'), ('GU', 'Guam'), ('IA', 'Iowa'), ('VI', 'U.S. Virgin Islands'), ('MD', 'Maryland'), ('NV', 'Nevada'), ('ME', 'Maine'), ('CA', 'California'), ('TX', 'Texas'), ('UT', 'Utah'), ('AL', 'Alabama'), ('GA', 'Georgia'), ('NJ', 'New Jersey'), ('KS', 'Kansas'), ('RI', 'Rhode Island'), ('LA', 'Louisiana')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='controlimplementation',
            name='progress',
            field=models.CharField(blank=True, choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Not Started', max_length=30, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='controlimplementation',
            unique_together={('control', 'system')},
        ),
        migrations.RemoveField(
            model_name='controlimplementation',
            name='status',
        ),
        migrations.AddField(
            model_name='controlimplementation',
            name='statuses',
            field=models.ManyToManyField(to='AlchemyApp.implementationstatus'),
        ),
    ]
