# Generated by Django 4.2 on 2023-04-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0008_customuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(blank=True, choices=[('Control Question', 'Control Quesition'), ('Overview Question', 'Overview Question'), ('Data Type Question', 'Data Type Question'), ('Impact Question', 'Impact Question')], default='Control Question', max_length=40),
        ),
        migrations.AlterField(
            model_name='question',
            name='controls',
            field=models.ManyToManyField(blank=True, to='AlchemyApp.nistcontrol'),
        ),
    ]
