# Generated by Django 4.2 on 2023-04-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0010_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(blank=True, choices=[('Control Question', 'Control Question'), ('Overview Question', 'Overview Question'), ('Data Type Question', 'Data Type Question'), ('Impact Question', 'Impact Question')], max_length=40),
        ),
    ]
