# Generated by Django 4.2 on 2023-05-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0012_alter_client_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.AddField(
            model_name='client',
            name='address1',
            field=models.CharField(blank=True, max_length=1024, null=True, unique=True, verbose_name='Address line 1'),
        ),
        migrations.AddField(
            model_name='client',
            name='address2',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Address line 2'),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('HI', 'Hawaii'), ('FL', 'Florida'), ('KS', 'Kansas'), ('IL', 'Illinois'), ('NH', 'New Hampshire'), ('SD', 'South Dakota'), ('WY', 'Wyoming'), ('AS', 'American Samoa'), ('MN', 'Minnesota'), ('DE', 'Delaware'), ('VT', 'Vermont'), ('OK', 'Oklahoma'), ('MT', 'Montana'), ('ND', 'North Dakota'), ('NV', 'Nevada'), ('ME', 'Maine'), ('MS', 'Mississippi'), ('PA', 'Pennsylvania'), ('NE', 'Nebraska'), ('TN', 'Tennessee'), ('UT', 'Utah'), ('TX', 'Texas'), ('AZ', 'Arizona'), ('KY', 'Kentucky'), ('MI', 'Michigan'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('OH', 'Ohio'), ('CT', 'Connecticut'), ('WI', 'Wisconsin'), ('IN', 'Indiana'), ('MA', 'Massachusetts'), ('VI', 'U.S. Virgin Islands'), ('IA', 'Iowa'), ('NY', 'New York'), ('MD', 'Maryland'), ('VA', 'Virginia'), ('ID', 'Idaho'), ('WV', 'West Virginia'), ('AK', 'Alaska'), ('CA', 'California'), ('OR', 'Oregon'), ('AL', 'Alabama'), ('GU', 'Guam'), ('MP', 'Northern Mariana Islands'), ('NC', 'North Carolina'), ('AR', 'Arkansas'), ('LA', 'Louisiana'), ('UM', 'United States Minor Outlying Islands'), ('GA', 'Georgia'), ('DC', 'District of Columbia'), ('MO', 'Missouri'), ('NJ', 'New Jersey'), ('SC', 'South Carolina'), ('NM', 'New Mexico'), ('WA', 'Washington'), ('CO', 'Colorado')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='client',
            name='zip_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ZIP / Postal code'),
        ),
    ]
