# Generated by Django 4.2 on 2023-05-01 00:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0013_remove_client_address_client_address1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system',
            old_name='owner',
            new_name='owner_name',
        ),
        migrations.AddField(
            model_name='system',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='system',
            name='owner_phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('CA', 'California'), ('WA', 'Washington'), ('CT', 'Connecticut'), ('NC', 'North Carolina'), ('VT', 'Vermont'), ('HI', 'Hawaii'), ('UM', 'United States Minor Outlying Islands'), ('AZ', 'Arizona'), ('IL', 'Illinois'), ('PR', 'Puerto Rico'), ('WI', 'Wisconsin'), ('MT', 'Montana'), ('OK', 'Oklahoma'), ('UT', 'Utah'), ('MO', 'Missouri'), ('TN', 'Tennessee'), ('AS', 'American Samoa'), ('OH', 'Ohio'), ('WV', 'West Virginia'), ('SD', 'South Dakota'), ('PA', 'Pennsylvania'), ('ID', 'Idaho'), ('NV', 'Nevada'), ('OR', 'Oregon'), ('MP', 'Northern Mariana Islands'), ('AK', 'Alaska'), ('AL', 'Alabama'), ('ME', 'Maine'), ('NE', 'Nebraska'), ('KS', 'Kansas'), ('MS', 'Mississippi'), ('FL', 'Florida'), ('GA', 'Georgia'), ('NY', 'New York'), ('VA', 'Virginia'), ('AR', 'Arkansas'), ('CO', 'Colorado'), ('LA', 'Louisiana'), ('NM', 'New Mexico'), ('GU', 'Guam'), ('DE', 'Delaware'), ('MN', 'Minnesota'), ('SC', 'South Carolina'), ('VI', 'U.S. Virgin Islands'), ('ND', 'North Dakota'), ('KY', 'Kentucky'), ('NJ', 'New Jersey'), ('MI', 'Michigan'), ('MA', 'Massachusetts'), ('MD', 'Maryland'), ('NH', 'New Hampshire'), ('WY', 'Wyoming'), ('DC', 'District of Columbia'), ('RI', 'Rhode Island'), ('TX', 'Texas'), ('IA', 'Iowa'), ('IN', 'Indiana')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
    ]
