# Generated by Django 4.2 on 2023-05-01 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0014_rename_owner_system_owner_name_system_owner_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('MT', 'Montana'), ('RI', 'Rhode Island'), ('OH', 'Ohio'), ('KY', 'Kentucky'), ('AL', 'Alabama'), ('KS', 'Kansas'), ('DE', 'Delaware'), ('ME', 'Maine'), ('AS', 'American Samoa'), ('TN', 'Tennessee'), ('NM', 'New Mexico'), ('LA', 'Louisiana'), ('MN', 'Minnesota'), ('GU', 'Guam'), ('HI', 'Hawaii'), ('MO', 'Missouri'), ('IN', 'Indiana'), ('NJ', 'New Jersey'), ('NE', 'Nebraska'), ('VA', 'Virginia'), ('MD', 'Maryland'), ('CT', 'Connecticut'), ('PA', 'Pennsylvania'), ('MP', 'Northern Mariana Islands'), ('OK', 'Oklahoma'), ('WI', 'Wisconsin'), ('FL', 'Florida'), ('OR', 'Oregon'), ('WV', 'West Virginia'), ('NC', 'North Carolina'), ('GA', 'Georgia'), ('AR', 'Arkansas'), ('NY', 'New York'), ('VT', 'Vermont'), ('SD', 'South Dakota'), ('UM', 'United States Minor Outlying Islands'), ('NV', 'Nevada'), ('AZ', 'Arizona'), ('UT', 'Utah'), ('WY', 'Wyoming'), ('TX', 'Texas'), ('DC', 'District of Columbia'), ('VI', 'U.S. Virgin Islands'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('NH', 'New Hampshire'), ('MS', 'Mississippi'), ('ND', 'North Dakota'), ('PR', 'Puerto Rico'), ('ID', 'Idaho'), ('WA', 'Washington'), ('AK', 'Alaska'), ('CA', 'California'), ('CO', 'Colorado'), ('IA', 'Iowa'), ('SC', 'South Carolina'), ('IL', 'Illinois')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
    ]
