# Generated by Django 4.2 on 2023-05-02 00:20

import AlchemyApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0015_alter_client_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address1',
            field=models.CharField(blank=True, max_length=1024, null=True, unique=True, validators=[AlchemyApp.models.Client.validate_street_address], verbose_name='Address line 1'),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=1024, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$', message='Enter a valid city name containing only letters and spaces.')], verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('KY', 'Kentucky'), ('MN', 'Minnesota'), ('TX', 'Texas'), ('MI', 'Michigan'), ('ND', 'North Dakota'), ('UT', 'Utah'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('MS', 'Mississippi'), ('AR', 'Arkansas'), ('NE', 'Nebraska'), ('NM', 'New Mexico'), ('AL', 'Alabama'), ('OK', 'Oklahoma'), ('VT', 'Vermont'), ('WI', 'Wisconsin'), ('GA', 'Georgia'), ('NC', 'North Carolina'), ('RI', 'Rhode Island'), ('VA', 'Virginia'), ('WY', 'Wyoming'), ('KS', 'Kansas'), ('VI', 'U.S. Virgin Islands'), ('CT', 'Connecticut'), ('LA', 'Louisiana'), ('IA', 'Iowa'), ('MP', 'Northern Mariana Islands'), ('GU', 'Guam'), ('SC', 'South Carolina'), ('MD', 'Maryland'), ('CA', 'California'), ('TN', 'Tennessee'), ('PR', 'Puerto Rico'), ('IL', 'Illinois'), ('DE', 'Delaware'), ('NY', 'New York'), ('SD', 'South Dakota'), ('MO', 'Missouri'), ('DC', 'District of Columbia'), ('HI', 'Hawaii'), ('UM', 'United States Minor Outlying Islands'), ('AS', 'American Samoa'), ('NJ', 'New Jersey'), ('ID', 'Idaho'), ('NV', 'Nevada'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('OH', 'Ohio'), ('WA', 'Washington'), ('MA', 'Massachusetts'), ('FL', 'Florida'), ('NH', 'New Hampshire'), ('ME', 'Maine'), ('WV', 'West Virginia'), ('IN', 'Indiana'), ('MT', 'Montana'), ('CO', 'Colorado')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='client',
            name='zip_code',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator('^\\d{5}(?:[-\\s]\\d{4})?$', message='Enter a valid U.S. ZIP code.')], verbose_name='ZIP / Postal code'),
        ),
    ]
