# Generated by Django 4.2 on 2023-05-02 00:50

import AlchemyApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0016_alter_client_address1_alter_client_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address1',
            field=models.CharField(blank=True, max_length=1024, null=True, validators=[AlchemyApp.models.Client.validate_street_address], verbose_name='Address line 1'),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('RI', 'Rhode Island'), ('AS', 'American Samoa'), ('DE', 'Delaware'), ('NH', 'New Hampshire'), ('CO', 'Colorado'), ('WY', 'Wyoming'), ('NM', 'New Mexico'), ('WI', 'Wisconsin'), ('ID', 'Idaho'), ('FL', 'Florida'), ('NV', 'Nevada'), ('AR', 'Arkansas'), ('SD', 'South Dakota'), ('AZ', 'Arizona'), ('OH', 'Ohio'), ('NY', 'New York'), ('NE', 'Nebraska'), ('MP', 'Northern Mariana Islands'), ('MO', 'Missouri'), ('AL', 'Alabama'), ('NJ', 'New Jersey'), ('MI', 'Michigan'), ('OK', 'Oklahoma'), ('TN', 'Tennessee'), ('GU', 'Guam'), ('KS', 'Kansas'), ('MT', 'Montana'), ('AK', 'Alaska'), ('HI', 'Hawaii'), ('IA', 'Iowa'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('PR', 'Puerto Rico'), ('TX', 'Texas'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('ND', 'North Dakota'), ('KY', 'Kentucky'), ('NC', 'North Carolina'), ('ME', 'Maine'), ('UT', 'Utah'), ('VT', 'Vermont'), ('LA', 'Louisiana'), ('MD', 'Maryland'), ('DC', 'District of Columbia'), ('CA', 'California'), ('PA', 'Pennsylvania'), ('SC', 'South Carolina'), ('VA', 'Virginia'), ('UM', 'United States Minor Outlying Islands'), ('OR', 'Oregon'), ('MS', 'Mississippi'), ('GA', 'Georgia'), ('MA', 'Massachusetts'), ('MN', 'Minnesota'), ('VI', 'U.S. Virgin Islands'), ('CT', 'Connecticut')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
    ]
