# Generated by Django 4.2 on 2023-05-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0017_alter_client_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('MT', 'Montana'), ('AS', 'American Samoa'), ('NM', 'New Mexico'), ('IL', 'Illinois'), ('NH', 'New Hampshire'), ('PA', 'Pennsylvania'), ('ND', 'North Dakota'), ('MP', 'Northern Mariana Islands'), ('TX', 'Texas'), ('AK', 'Alaska'), ('FL', 'Florida'), ('ID', 'Idaho'), ('MD', 'Maryland'), ('MO', 'Missouri'), ('DC', 'District of Columbia'), ('PR', 'Puerto Rico'), ('GA', 'Georgia'), ('UM', 'United States Minor Outlying Islands'), ('WY', 'Wyoming'), ('SD', 'South Dakota'), ('WV', 'West Virginia'), ('VI', 'U.S. Virgin Islands'), ('NC', 'North Carolina'), ('MN', 'Minnesota'), ('CO', 'Colorado'), ('ME', 'Maine'), ('AL', 'Alabama'), ('NV', 'Nevada'), ('AZ', 'Arizona'), ('IA', 'Iowa'), ('MI', 'Michigan'), ('TN', 'Tennessee'), ('VT', 'Vermont'), ('SC', 'South Carolina'), ('WI', 'Wisconsin'), ('MS', 'Mississippi'), ('VA', 'Virginia'), ('NY', 'New York'), ('OK', 'Oklahoma'), ('CA', 'California'), ('HI', 'Hawaii'), ('OR', 'Oregon'), ('OH', 'Ohio'), ('MA', 'Massachusetts'), ('DE', 'Delaware'), ('KS', 'Kansas'), ('LA', 'Louisiana'), ('IN', 'Indiana'), ('NJ', 'New Jersey'), ('WA', 'Washington'), ('CT', 'Connecticut'), ('RI', 'Rhode Island'), ('KY', 'Kentucky'), ('NE', 'Nebraska'), ('UT', 'Utah'), ('GU', 'Guam'), ('AR', 'Arkansas')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
    ]
