# Generated by Django 4.2 on 2023-05-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0017_alter_client_address1_alter_client_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('CO', 'Colorado'), ('CT', 'Connecticut'), ('ID', 'Idaho'), ('NV', 'Nevada'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('VT', 'Vermont'), ('MO', 'Missouri'), ('MD', 'Maryland'), ('SC', 'South Carolina'), ('NJ', 'New Jersey'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('HI', 'Hawaii'), ('RI', 'Rhode Island'), ('AS', 'American Samoa'), ('DE', 'Delaware'), ('NY', 'New York'), ('VI', 'U.S. Virgin Islands'), ('OH', 'Ohio'), ('GU', 'Guam'), ('AZ', 'Arizona'), ('IN', 'Indiana'), ('MS', 'Mississippi'), ('VA', 'Virginia'), ('AR', 'Arkansas'), ('IL', 'Illinois'), ('GA', 'Georgia'), ('SD', 'South Dakota'), ('ND', 'North Dakota'), ('DC', 'District of Columbia'), ('PR', 'Puerto Rico'), ('MT', 'Montana'), ('NM', 'New Mexico'), ('NE', 'Nebraska'), ('OK', 'Oklahoma'), ('UT', 'Utah'), ('LA', 'Louisiana'), ('TN', 'Tennessee'), ('ME', 'Maine'), ('PA', 'Pennsylvania'), ('CA', 'California'), ('TX', 'Texas'), ('MP', 'Northern Mariana Islands'), ('NH', 'New Hampshire'), ('MI', 'Michigan'), ('AL', 'Alabama'), ('WY', 'Wyoming'), ('NC', 'North Carolina'), ('UM', 'United States Minor Outlying Islands'), ('MN', 'Minnesota'), ('AK', 'Alaska'), ('KY', 'Kentucky'), ('WA', 'Washington'), ('FL', 'Florida'), ('MA', 'Massachusetts'), ('OR', 'Oregon')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
    ]
