# Generated by Django 4.2 on 2023-05-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0018_alter_client_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('PR', 'Puerto Rico'), ('WV', 'West Virginia'), ('MP', 'Northern Mariana Islands'), ('AK', 'Alaska'), ('UT', 'Utah'), ('VA', 'Virginia'), ('CA', 'California'), ('OR', 'Oregon'), ('WA', 'Washington'), ('KS', 'Kansas'), ('WY', 'Wyoming'), ('NC', 'North Carolina'), ('OK', 'Oklahoma'), ('AZ', 'Arizona'), ('MN', 'Minnesota'), ('NV', 'Nevada'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('SD', 'South Dakota'), ('IN', 'Indiana'), ('WI', 'Wisconsin'), ('TX', 'Texas'), ('DC', 'District of Columbia'), ('GU', 'Guam'), ('NH', 'New Hampshire'), ('MT', 'Montana'), ('ND', 'North Dakota'), ('MI', 'Michigan'), ('IA', 'Iowa'), ('ME', 'Maine'), ('NE', 'Nebraska'), ('LA', 'Louisiana'), ('CO', 'Colorado'), ('AR', 'Arkansas'), ('PA', 'Pennsylvania'), ('HI', 'Hawaii'), ('MS', 'Mississippi'), ('VT', 'Vermont'), ('MD', 'Maryland'), ('SC', 'South Carolina'), ('DE', 'Delaware'), ('RI', 'Rhode Island'), ('FL', 'Florida'), ('NM', 'New Mexico'), ('UM', 'United States Minor Outlying Islands'), ('MO', 'Missouri'), ('TN', 'Tennessee'), ('MA', 'Massachusetts'), ('AS', 'American Samoa'), ('CT', 'Connecticut'), ('VI', 'U.S. Virgin Islands'), ('NJ', 'New Jersey'), ('GA', 'Georgia'), ('KY', 'Kentucky'), ('NY', 'New York'), ('AL', 'Alabama'), ('OH', 'Ohio')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
    ]
