# Generated by Django 4.2 on 2023-05-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0018_alter_client_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlimplementation',
            name='statement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('CA', 'California'), ('IN', 'Indiana'), ('ND', 'North Dakota'), ('OR', 'Oregon'), ('NJ', 'New Jersey'), ('SC', 'South Carolina'), ('MO', 'Missouri'), ('CO', 'Colorado'), ('UM', 'United States Minor Outlying Islands'), ('NM', 'New Mexico'), ('MS', 'Mississippi'), ('IL', 'Illinois'), ('PR', 'Puerto Rico'), ('DE', 'Delaware'), ('AL', 'Alabama'), ('WA', 'Washington'), ('FL', 'Florida'), ('ID', 'Idaho'), ('DC', 'District of Columbia'), ('NE', 'Nebraska'), ('IA', 'Iowa'), ('WV', 'West Virginia'), ('GU', 'Guam'), ('SD', 'South Dakota'), ('ME', 'Maine'), ('VT', 'Vermont'), ('WI', 'Wisconsin'), ('HI', 'Hawaii'), ('CT', 'Connecticut'), ('MT', 'Montana'), ('RI', 'Rhode Island'), ('WY', 'Wyoming'), ('TX', 'Texas'), ('VA', 'Virginia'), ('LA', 'Louisiana'), ('MA', 'Massachusetts'), ('NV', 'Nevada'), ('MI', 'Michigan'), ('KS', 'Kansas'), ('AZ', 'Arizona'), ('KY', 'Kentucky'), ('AK', 'Alaska'), ('VI', 'U.S. Virgin Islands'), ('GA', 'Georgia'), ('NY', 'New York'), ('MN', 'Minnesota'), ('OH', 'Ohio'), ('NH', 'New Hampshire'), ('TN', 'Tennessee'), ('OK', 'Oklahoma'), ('PA', 'Pennsylvania'), ('AS', 'American Samoa'), ('NC', 'North Carolina'), ('UT', 'Utah'), ('MP', 'Northern Mariana Islands'), ('MD', 'Maryland'), ('AR', 'Arkansas')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
    ]
