# Generated by Django 4.2 on 2023-05-02 01:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0019_alter_client_client_name_alter_client_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('VT', 'Vermont'), ('AL', 'Alabama'), ('WV', 'West Virginia'), ('DE', 'Delaware'), ('PR', 'Puerto Rico'), ('AS', 'American Samoa'), ('FL', 'Florida'), ('MO', 'Missouri'), ('NE', 'Nebraska'), ('KS', 'Kansas'), ('MS', 'Mississippi'), ('AR', 'Arkansas'), ('GU', 'Guam'), ('NH', 'New Hampshire'), ('CT', 'Connecticut'), ('NV', 'Nevada'), ('KY', 'Kentucky'), ('NM', 'New Mexico'), ('MT', 'Montana'), ('ID', 'Idaho'), ('AZ', 'Arizona'), ('WY', 'Wyoming'), ('SC', 'South Carolina'), ('NY', 'New York'), ('IA', 'Iowa'), ('MD', 'Maryland'), ('OH', 'Ohio'), ('ME', 'Maine'), ('NJ', 'New Jersey'), ('OR', 'Oregon'), ('SD', 'South Dakota'), ('NC', 'North Carolina'), ('TX', 'Texas'), ('WI', 'Wisconsin'), ('MA', 'Massachusetts'), ('ND', 'North Dakota'), ('OK', 'Oklahoma'), ('GA', 'Georgia'), ('UT', 'Utah'), ('VA', 'Virginia'), ('LA', 'Louisiana'), ('WA', 'Washington'), ('MP', 'Northern Mariana Islands'), ('IL', 'Illinois'), ('AK', 'Alaska'), ('PA', 'Pennsylvania'), ('DC', 'District of Columbia'), ('MN', 'Minnesota'), ('VI', 'U.S. Virgin Islands'), ('CA', 'California'), ('HI', 'Hawaii'), ('TN', 'Tennessee'), ('RI', 'Rhode Island'), ('UM', 'United States Minor Outlying Islands'), ('MI', 'Michigan'), ('IN', 'Indiana'), ('CO', 'Colorado')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
    ]
