# Generated by Django 4.2 on 2023-05-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0020_alter_client_client_name_alter_client_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='color',
            field=models.CharField(default='DBEAFE', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('OH', 'Ohio'), ('SD', 'South Dakota'), ('UT', 'Utah'), ('FL', 'Florida'), ('KS', 'Kansas'), ('LA', 'Louisiana'), ('AZ', 'Arizona'), ('MO', 'Missouri'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('WV', 'West Virginia'), ('MN', 'Minnesota'), ('VA', 'Virginia'), ('MS', 'Mississippi'), ('VI', 'U.S. Virgin Islands'), ('MI', 'Michigan'), ('ID', 'Idaho'), ('WA', 'Washington'), ('CO', 'Colorado'), ('NJ', 'New Jersey'), ('KY', 'Kentucky'), ('GU', 'Guam'), ('NY', 'New York'), ('ND', 'North Dakota'), ('HI', 'Hawaii'), ('AL', 'Alabama'), ('MA', 'Massachusetts'), ('NH', 'New Hampshire'), ('MT', 'Montana'), ('NM', 'New Mexico'), ('PA', 'Pennsylvania'), ('WY', 'Wyoming'), ('UM', 'United States Minor Outlying Islands'), ('NE', 'Nebraska'), ('AS', 'American Samoa'), ('PR', 'Puerto Rico'), ('TN', 'Tennessee'), ('WI', 'Wisconsin'), ('RI', 'Rhode Island'), ('TX', 'Texas'), ('AK', 'Alaska'), ('GA', 'Georgia'), ('IL', 'Illinois'), ('ME', 'Maine'), ('AR', 'Arkansas'), ('VT', 'Vermont'), ('MP', 'Northern Mariana Islands'), ('IA', 'Iowa'), ('MD', 'Maryland'), ('NV', 'Nevada'), ('IN', 'Indiana'), ('DC', 'District of Columbia'), ('OK', 'Oklahoma'), ('CA', 'California'), ('NC', 'North Carolina'), ('OR', 'Oregon'), ('SC', 'South Carolina')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
