# Generated by Django 4.2 on 2023-05-03 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0021_system_color_alter_client_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('MO', 'Missouri'), ('RI', 'Rhode Island'), ('VA', 'Virginia'), ('KY', 'Kentucky'), ('PA', 'Pennsylvania'), ('TN', 'Tennessee'), ('OR', 'Oregon'), ('AZ', 'Arizona'), ('LA', 'Louisiana'), ('CO', 'Colorado'), ('IA', 'Iowa'), ('VT', 'Vermont'), ('TX', 'Texas'), ('MS', 'Mississippi'), ('ND', 'North Dakota'), ('VI', 'U.S. Virgin Islands'), ('UM', 'United States Minor Outlying Islands'), ('IN', 'Indiana'), ('OH', 'Ohio'), ('IL', 'Illinois'), ('ME', 'Maine'), ('WA', 'Washington'), ('MA', 'Massachusetts'), ('MN', 'Minnesota'), ('GA', 'Georgia'), ('KS', 'Kansas'), ('DC', 'District of Columbia'), ('AK', 'Alaska'), ('WI', 'Wisconsin'), ('PR', 'Puerto Rico'), ('NY', 'New York'), ('AL', 'Alabama'), ('MP', 'Northern Mariana Islands'), ('NJ', 'New Jersey'), ('AS', 'American Samoa'), ('HI', 'Hawaii'), ('MI', 'Michigan'), ('MT', 'Montana'), ('DE', 'Delaware'), ('CT', 'Connecticut'), ('NE', 'Nebraska'), ('NH', 'New Hampshire'), ('ID', 'Idaho'), ('NC', 'North Carolina'), ('WV', 'West Virginia'), ('MD', 'Maryland'), ('UT', 'Utah'), ('GU', 'Guam'), ('FL', 'Florida'), ('NM', 'New Mexico'), ('CA', 'California'), ('WY', 'Wyoming'), ('SC', 'South Carolina'), ('OK', 'Oklahoma'), ('NV', 'Nevada'), ('AR', 'Arkansas'), ('SD', 'South Dakota')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
