# Generated by Django 4.2 on 2023-05-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0022_alter_client_state_alter_customuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('VA', 'Virginia'), ('OR', 'Oregon'), ('AR', 'Arkansas'), ('WA', 'Washington'), ('PA', 'Pennsylvania'), ('MA', 'Massachusetts'), ('AK', 'Alaska'), ('NM', 'New Mexico'), ('ID', 'Idaho'), ('NC', 'North Carolina'), ('MI', 'Michigan'), ('IA', 'Iowa'), ('NE', 'Nebraska'), ('VT', 'Vermont'), ('GU', 'Guam'), ('MP', 'Northern Mariana Islands'), ('VI', 'U.S. Virgin Islands'), ('TX', 'Texas'), ('WI', 'Wisconsin'), ('AL', 'Alabama'), ('WY', 'Wyoming'), ('NY', 'New York'), ('FL', 'Florida'), ('DC', 'District of Columbia'), ('LA', 'Louisiana'), ('MO', 'Missouri'), ('HI', 'Hawaii'), ('OH', 'Ohio'), ('SD', 'South Dakota'), ('AZ', 'Arizona'), ('CA', 'California'), ('DE', 'Delaware'), ('CO', 'Colorado'), ('WV', 'West Virginia'), ('MD', 'Maryland'), ('AS', 'American Samoa'), ('UT', 'Utah'), ('ME', 'Maine'), ('OK', 'Oklahoma'), ('NH', 'New Hampshire'), ('IL', 'Illinois'), ('ND', 'North Dakota'), ('MS', 'Mississippi'), ('TN', 'Tennessee'), ('UM', 'United States Minor Outlying Islands'), ('MN', 'Minnesota'), ('GA', 'Georgia'), ('IN', 'Indiana'), ('SC', 'South Carolina'), ('RI', 'Rhode Island'), ('PR', 'Puerto Rico'), ('NV', 'Nevada'), ('KS', 'Kansas'), ('NJ', 'New Jersey'), ('CT', 'Connecticut'), ('MT', 'Montana'), ('KY', 'Kentucky')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
        migrations.AlterUniqueTogether(
            name='system',
            unique_together={('name', 'client')},
        ),
    ]
