# Generated by Django 4.2 on 2023-05-04 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0023_alter_client_state_alter_system_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AlchemyApp.system'),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('MD', 'Maryland'), ('ID', 'Idaho'), ('MT', 'Montana'), ('PA', 'Pennsylvania'), ('SD', 'South Dakota'), ('UT', 'Utah'), ('KY', 'Kentucky'), ('ME', 'Maine'), ('TX', 'Texas'), ('KS', 'Kansas'), ('AZ', 'Arizona'), ('NE', 'Nebraska'), ('PR', 'Puerto Rico'), ('WI', 'Wisconsin'), ('IL', 'Illinois'), ('WV', 'West Virginia'), ('DE', 'Delaware'), ('IN', 'Indiana'), ('CA', 'California'), ('NC', 'North Carolina'), ('AR', 'Arkansas'), ('WY', 'Wyoming'), ('VI', 'U.S. Virgin Islands'), ('NV', 'Nevada'), ('FL', 'Florida'), ('TN', 'Tennessee'), ('MO', 'Missouri'), ('ND', 'North Dakota'), ('GA', 'Georgia'), ('NJ', 'New Jersey'), ('OR', 'Oregon'), ('AS', 'American Samoa'), ('RI', 'Rhode Island'), ('CO', 'Colorado'), ('HI', 'Hawaii'), ('DC', 'District of Columbia'), ('MP', 'Northern Mariana Islands'), ('GU', 'Guam'), ('LA', 'Louisiana'), ('UM', 'United States Minor Outlying Islands'), ('OH', 'Ohio'), ('NM', 'New Mexico'), ('VA', 'Virginia'), ('AK', 'Alaska'), ('IA', 'Iowa'), ('MN', 'Minnesota'), ('CT', 'Connecticut'), ('NY', 'New York'), ('OK', 'Oklahoma'), ('WA', 'Washington'), ('MA', 'Massachusetts'), ('SC', 'South Carolina'), ('AL', 'Alabama'), ('MS', 'Mississippi'), ('NH', 'New Hampshire'), ('VT', 'Vermont'), ('MI', 'Michigan')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
    ]
