# Generated by Django 4.2 on 2023-05-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0024_alter_answer_system_alter_client_state'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='system',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('HI', 'Hawaii'), ('FL', 'Florida'), ('OH', 'Ohio'), ('MS', 'Mississippi'), ('PR', 'Puerto Rico'), ('AL', 'Alabama'), ('AR', 'Arkansas'), ('WV', 'West Virginia'), ('NV', 'Nevada'), ('SC', 'South Carolina'), ('MT', 'Montana'), ('NY', 'New York'), ('VA', 'Virginia'), ('MN', 'Minnesota'), ('NJ', 'New Jersey'), ('WY', 'Wyoming'), ('MD', 'Maryland'), ('RI', 'Rhode Island'), ('NH', 'New Hampshire'), ('WI', 'Wisconsin'), ('MP', 'Northern Mariana Islands'), ('KY', 'Kentucky'), ('AS', 'American Samoa'), ('DE', 'Delaware'), ('ID', 'Idaho'), ('VI', 'U.S. Virgin Islands'), ('TX', 'Texas'), ('GA', 'Georgia'), ('OR', 'Oregon'), ('TN', 'Tennessee'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MO', 'Missouri'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('WA', 'Washington'), ('SD', 'South Dakota'), ('DC', 'District of Columbia'), ('CO', 'Colorado'), ('VT', 'Vermont'), ('NE', 'Nebraska'), ('GU', 'Guam'), ('IA', 'Iowa'), ('IN', 'Indiana'), ('NM', 'New Mexico'), ('CT', 'Connecticut'), ('KS', 'Kansas'), ('AK', 'Alaska'), ('UT', 'Utah'), ('LA', 'Louisiana'), ('PA', 'Pennsylvania'), ('ME', 'Maine'), ('OK', 'Oklahoma'), ('CA', 'California'), ('UM', 'United States Minor Outlying Islands'), ('IL', 'Illinois'), ('AZ', 'Arizona')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
    ]
