# Generated by Django 4.2 on 2023-05-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0025_alter_system_unique_together_alter_client_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('NH', 'New Hampshire'), ('OR', 'Oregon'), ('NM', 'New Mexico'), ('OK', 'Oklahoma'), ('CO', 'Colorado'), ('KY', 'Kentucky'), ('PR', 'Puerto Rico'), ('DE', 'Delaware'), ('IN', 'Indiana'), ('AR', 'Arkansas'), ('ND', 'North Dakota'), ('SC', 'South Carolina'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('MN', 'Minnesota'), ('GU', 'Guam'), ('LA', 'Louisiana'), ('RI', 'Rhode Island'), ('FL', 'Florida'), ('ID', 'Idaho'), ('MO', 'Missouri'), ('MT', 'Montana'), ('GA', 'Georgia'), ('VA', 'Virginia'), ('DC', 'District of Columbia'), ('WY', 'Wyoming'), ('VI', 'U.S. Virgin Islands'), ('KS', 'Kansas'), ('AZ', 'Arizona'), ('OH', 'Ohio'), ('NV', 'Nevada'), ('MD', 'Maryland'), ('CA', 'California'), ('ME', 'Maine'), ('NJ', 'New Jersey'), ('IL', 'Illinois'), ('IA', 'Iowa'), ('NE', 'Nebraska'), ('UM', 'United States Minor Outlying Islands'), ('NC', 'North Carolina'), ('AS', 'American Samoa'), ('MS', 'Mississippi'), ('AL', 'Alabama'), ('NY', 'New York'), ('WI', 'Wisconsin'), ('MA', 'Massachusetts'), ('UT', 'Utah'), ('MP', 'Northern Mariana Islands'), ('SD', 'South Dakota'), ('VT', 'Vermont'), ('TX', 'Texas'), ('PA', 'Pennsylvania'), ('TN', 'Tennessee'), ('AK', 'Alaska'), ('CT', 'Connecticut'), ('HI', 'Hawaii'), ('MI', 'Michigan')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
        migrations.AlterUniqueTogether(
            name='system',
            unique_together={('name', 'client')},
        ),
    ]
