# Generated by Django 4.2 on 2023-05-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0027_alter_client_state'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('GA', 'Georgia'), ('RI', 'Rhode Island'), ('CA', 'California'), ('SC', 'South Carolina'), ('UT', 'Utah'), ('MN', 'Minnesota'), ('WV', 'West Virginia'), ('NY', 'New York'), ('UM', 'United States Minor Outlying Islands'), ('MS', 'Mississippi'), ('ND', 'North Dakota'), ('IL', 'Illinois'), ('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('GU', 'Guam'), ('MP', 'Northern Mariana Islands'), ('NM', 'New Mexico'), ('OH', 'Ohio'), ('LA', 'Louisiana'), ('MO', 'Missouri'), ('OR', 'Oregon'), ('VT', 'Vermont'), ('WI', 'Wisconsin'), ('VI', 'U.S. Virgin Islands'), ('FL', 'Florida'), ('HI', 'Hawaii'), ('ME', 'Maine'), ('SD', 'South Dakota'), ('AS', 'American Samoa'), ('WA', 'Washington'), ('ID', 'Idaho'), ('NC', 'North Carolina'), ('KY', 'Kentucky'), ('PR', 'Puerto Rico'), ('CT', 'Connecticut'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('CO', 'Colorado'), ('DC', 'District of Columbia'), ('DE', 'Delaware'), ('MT', 'Montana'), ('VA', 'Virginia'), ('MA', 'Massachusetts'), ('IN', 'Indiana'), ('KS', 'Kansas'), ('MD', 'Maryland'), ('NE', 'Nebraska'), ('TN', 'Tennessee'), ('OK', 'Oklahoma'), ('WY', 'Wyoming'), ('AR', 'Arkansas'), ('TX', 'Texas'), ('NJ', 'New Jersey'), ('PA', 'Pennsylvania'), ('MI', 'Michigan'), ('IA', 'Iowa')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
    ]
