# Generated by Django 4.2 on 2023-05-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyApp', '0028_alter_answer_unique_together_alter_client_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, choices=[('MT', 'Montana'), ('OH', 'Ohio'), ('VT', 'Vermont'), ('NE', 'Nebraska'), ('NY', 'New York'), ('SD', 'South Dakota'), ('ID', 'Idaho'), ('GU', 'Guam'), ('ME', 'Maine'), ('MI', 'Michigan'), ('MD', 'Maryland'), ('VA', 'Virginia'), ('WA', 'Washington'), ('LA', 'Louisiana'), ('MS', 'Mississippi'), ('NV', 'Nevada'), ('TN', 'Tennessee'), ('IL', 'Illinois'), ('MP', 'Northern Mariana Islands'), ('OK', 'Oklahoma'), ('NC', 'North Carolina'), ('AS', 'American Samoa'), ('CT', 'Connecticut'), ('AL', 'Alabama'), ('UT', 'Utah'), ('NH', 'New Hampshire'), ('OR', 'Oregon'), ('AK', 'Alaska'), ('PR', 'Puerto Rico'), ('NM', 'New Mexico'), ('SC', 'South Carolina'), ('CA', 'California'), ('KY', 'Kentucky'), ('WV', 'West Virginia'), ('MA', 'Massachusetts'), ('MN', 'Minnesota'), ('WI', 'Wisconsin'), ('RI', 'Rhode Island'), ('DC', 'District of Columbia'), ('AR', 'Arkansas'), ('UM', 'United States Minor Outlying Islands'), ('VI', 'U.S. Virgin Islands'), ('MO', 'Missouri'), ('KS', 'Kansas'), ('WY', 'Wyoming'), ('HI', 'Hawaii'), ('PA', 'Pennsylvania'), ('NJ', 'New Jersey'), ('TX', 'Texas'), ('ND', 'North Dakota'), ('IA', 'Iowa'), ('CO', 'Colorado'), ('DE', 'Delaware'), ('IN', 'Indiana'), ('FL', 'Florida'), ('AZ', 'Arizona'), ('GA', 'Georgia')], default=None, max_length=2, null=True, verbose_name='State'),
        ),
    ]
